import type { Family, Rule } from './types';
const definitions: [
    Family,
    string,
    string,
    string
][] = [
    ['Identity', 'Suspicious login sequence', 'T1078', 'Initial Access'], ['Identity', 'Password spraying across accounts', 'T1110.003', 'Credential Access'], ['Identity', 'Repeated password guessing', 'T1110.001', 'Credential Access'], ['Identity', 'Credential stuffing pattern', 'T1110.004', 'Credential Access'], ['Identity', 'Geographically separated sign-ins', 'T1078', 'Initial Access'], ['Identity', 'Repeated MFA prompts', 'T1621', 'Credential Access'], ['Identity', 'Multiple failed logons', 'T1110.001', 'Credential Access'], ['Identity', 'Success after authentication failures', 'T1078', 'Initial Access'], ['Identity', 'First sign-in from a new country', 'T1078', 'Initial Access'], ['Identity', 'Sign-in from an anonymizing relay', 'T1090.003', 'Command and Control'], ['Identity', 'VPN session outside baseline', 'T1133', 'Initial Access'], ['Identity', 'Disabled account authentication', 'T1078', 'Initial Access'],
    ['Email', 'Message with credential collection link', 'T1566.002', 'Initial Access'], ['Email', 'Targeted invoice message', 'T1566.001', 'Initial Access'], ['Email', 'Unusual attachment delivery', 'T1566.001', 'Initial Access'], ['Email', 'URL redirect policy detection', 'T1566.002', 'Initial Access'], ['Email', 'Sign-in portal in external message', 'T1566.002', 'Initial Access'], ['Email', 'Sender authentication mismatch', 'T1566', 'Initial Access'], ['Email', 'Lookalike sender domain', 'T1566.002', 'Initial Access'], ['Email', 'Payment instruction change', 'T1534', 'Lateral Movement'], ['Email', 'QR code linking to sign-in form', 'T1566.002', 'Initial Access'], ['Email', 'HTML attachment creates a file', 'T1027.006', 'Defense Evasion'],
    ['Malware', 'Unfamiliar executable on endpoint', 'T1204.002', 'Execution'], ['Malware', 'Executable launched from archive', 'T1204.002', 'Execution'], ['Malware', 'Rapid file rename and write activity', 'T1486', 'Impact'], ['Malware', 'Browser credential store accessed', 'T1555.003', 'Credential Access'], ['Malware', 'Script initiates file download', 'T1105', 'Command and Control'], ['Malware', 'Unregistered remote access process', 'T1219', 'Command and Control'], ['Malware', 'Sustained compute and pool connection', 'T1496', 'Impact'], ['Malware', 'PowerShell starts after document open', 'T1059.001', 'Execution'], ['Malware', 'Script launched from temporary folder', 'T1059.005', 'Execution'], ['Malware', 'Encoded PowerShell command', 'T1059.001', 'Execution'], ['Malware', 'Signed utility loads remote content', 'T1218', 'Defense Evasion'],
    ['Endpoint', 'Unusual parent-child process chain', 'T1059', 'Execution'], ['Endpoint', 'Cross-process memory write', 'T1055', 'Defense Evasion'], ['Endpoint', 'Credential material access', 'T1003', 'Credential Access'], ['Endpoint', 'Process opened LSASS handle', 'T1003.001', 'Credential Access'], ['Endpoint', 'Credential extraction behavior', 'T1003.001', 'Credential Access'], ['Endpoint', 'New automatic startup entry', 'T1547', 'Persistence'], ['Endpoint', 'Registry Run key changed', 'T1547.001', 'Persistence'], ['Endpoint', 'Scheduled task registered', 'T1053.005', 'Persistence'], ['Endpoint', 'New service installed', 'T1543.003', 'Persistence'], ['Endpoint', 'DLL loaded from writable directory', 'T1574.001', 'Defense Evasion'], ['Endpoint', 'Unsigned executable started', 'T1204.002', 'Execution'], ['Endpoint', 'Endpoint behavior threshold exceeded', 'T1059', 'Execution'], ['Endpoint', 'Security service configuration changed', 'T1562.001', 'Defense Evasion'],
    ['Lateral movement', 'Remote access across endpoints', 'T1021', 'Lateral Movement'], ['Lateral movement', 'RDP to a second workstation', 'T1021.001', 'Lateral Movement'], ['Lateral movement', 'SMB access between workstations', 'T1021.002', 'Lateral Movement'], ['Lateral movement', 'Remote service process observed', 'T1569.002', 'Execution'], ['Lateral movement', 'WMI remote process creation', 'T1047', 'Execution'], ['Lateral movement', 'New WinRM connection', 'T1021.006', 'Lateral Movement'], ['Lateral movement', 'Remote service installation', 'T1543.003', 'Persistence'], ['Lateral movement', 'Administrative share access', 'T1021.002', 'Lateral Movement'], ['Lateral movement', 'NTLM logon without preceding interactive logon', 'T1550.002', 'Defense Evasion'], ['Lateral movement', 'Kerberos service ticket outside baseline', 'T1550.003', 'Defense Evasion'],
    ['Network', 'Sequential destination ports', 'T1046', 'Discovery'], ['Network', 'Internal network enumeration', 'T1046', 'Discovery'], ['Network', 'Regular outbound connection intervals', 'T1071.001', 'Command and Control'], ['Network', 'DNS query pattern deviation', 'T1071.004', 'Command and Control'], ['Network', 'High entropy DNS labels', 'T1071.004', 'Command and Control'], ['Network', 'Outbound transfer above baseline', 'T1041', 'Exfiltration'], ['Network', 'Connection matches intelligence feed', 'T1071', 'Command and Control'], ['Network', 'Traffic to an anonymizing relay', 'T1090.003', 'Command and Control'], ['Network', 'Sensitive archive uploaded externally', 'T1567', 'Exfiltration'], ['Network', 'Large HTTPS upload', 'T1567.002', 'Exfiltration'], ['Network', 'Protocol on an uncommon port', 'T1571', 'Command and Control'], ['Network', 'Repeated connections to one destination', 'T1071.001', 'Command and Control'],
    ['Web', 'SQL syntax in request parameters', 'T1190', 'Initial Access'], ['Web', 'Script markup in web request', 'T1190', 'Initial Access'], ['Web', 'Parent directory sequence in request', 'T1190', 'Initial Access'], ['Web', 'Shell syntax in request parameter', 'T1190', 'Initial Access'], ['Web', 'Web worker spawns a shell', 'T1505.003', 'Persistence'], ['Web', 'Unusual HTTP user agent', 'T1190', 'Initial Access'], ['Web', 'Web authentication burst', 'T1110', 'Credential Access'],
    ['Privilege', 'New privileged user account', 'T1136', 'Persistence'], ['Privilege', 'User added to local administrators', 'T1098', 'Persistence'], ['Privilege', 'Access token duplication', 'T1134', 'Privilege Escalation'], ['Privilege', 'sudo use outside role baseline', 'T1548.003', 'Privilege Escalation'], ['Privilege', 'Privileged group membership changed', 'T1098', 'Persistence'],
    ['Cloud', 'OAuth application consent granted', 'T1528', 'Credential Access'], ['Cloud', 'Cloud sign-in risk detection', 'T1078.004', 'Initial Access'], ['Cloud', 'Cloud session behavior deviation', 'T1078.004', 'Initial Access'], ['Cloud', 'API key usage from new network', 'T1078.004', 'Initial Access'], ['Cloud', 'Application granted mailbox access', 'T1098.002', 'Persistence'], ['Cloud', 'Identity provider risky sign-in', 'T1078.004', 'Initial Access'],
    ['Insider', 'File access volume exceeds baseline', 'T1213', 'Collection'], ['Insider', 'Removable media write activity', 'T1052.001', 'Exfiltration'], ['Insider', 'Large file transfer by user', 'T1030', 'Exfiltration'], ['Insider', 'Sensitive document access', 'T1213', 'Collection'], ['Insider', 'Access outside normal working hours', 'T1078', 'Initial Access']
];
export const sources: Record<Family, string> = { Identity: 'Identity Protection', Email: 'Email Gateway', Malware: 'Endpoint Sensor', Endpoint: 'Endpoint Sensor', 'Lateral movement': 'Windows Security', Network: 'Network Analytics', Web: 'Web Application Firewall', Privilege: 'Windows Security', Cloud: 'Cloud Audit', Insider: 'Data Protection' };
const logic: Record<Family, string> = { Identity: 'Authentication outcomes exceed the account or network baseline. Correlate raw record IDs, device trust, MFA and session continuity.', Email: 'Message content, routing or sender-authentication signals match the configured gateway policy.', Malware: 'Process, file or connection behavior exceeds the endpoint behavior threshold.', Endpoint: 'Process, persistence or security configuration telemetry matches a sensor policy.', 'Lateral movement': 'Remote authentication, administrative shares or execution connect multiple endpoints.', Network: 'Flow, DNS or proxy metadata differs from the established traffic baseline.', Web: 'HTTP request syntax or web-worker behavior matches a WAF or endpoint audit condition.', Privilege: 'A privileged operation is observed outside the normal account role.', Cloud: 'Application consent, API or identity activity differs from tenant baselines.', Insider: 'File access, removable media or transfer volume differs from the user baseline.' };
export const rules: Rule[] = definitions.map(([family, name, technique, tactic], i) => ({ id: `DET-${String(i + 1).padStart(3, '0')}`, name, family, technique, tactic, source: sources[family], logic: logic[family], description: `Review ${name.toLowerCase()} using the source records and correlated identity, endpoint, network and business context.` }));
export const families = Object.keys(sources) as Family[];
export const severities = ['Critical', 'High', 'Medium', 'Low'] as const;
export const verdicts = ['True Positive', 'False Positive', 'Benign Positive', 'Needs More Investigation'];
export const dispositions = ['Escalate to L2', 'Escalate to Incident Response', 'Close Alert', 'Monitor', 'Containment Recommended'];
export const worksheetFields = [['observedActivity', 'Observed activity'], ['evidenceReviewed', 'Evidence reviewed'], ['iocFindings', 'IOC findings'], ['endpointFindings', 'Endpoint findings'], ['authenticationFindings', 'Authentication findings'], ['networkFindings', 'Network findings'], ['scope', 'Scope assessment'], ['affectedAssets', 'Affected assets'], ['actionTaken', 'Actions taken'], ['escalationReason', 'Escalation reason'], ['nextStep', 'Recommended next step'], ['notes', 'Analyst notes']] as const;
