import { users, hosts } from './entities';
import { rules } from './catalog';
import { rng, pick, int, fauxHash, EPOCH, iso, externalIP } from './random';
import { improveScenario } from './scenario-quality';
import { addCategoryEvidence } from './scenario-features';
import type { Alert, GroundTruth, IOC, LabEvent, Scenario, Severity } from './types';
export interface Injection {
    category?: string;
    severity?: Severity;
    user?: string;
    host?: string;
    ioc?: string;
    timestamp?: string;
    difficulty?: string;
    seed?: number;
}
const campaignRules = [[0, 7, 31, 58, 47], [12, 14, 29, 58, 35], [80, 82, 84, 18, 64]];
const campaignNames = ['Identity and endpoint sequence', 'Message and endpoint sequence', 'Cloud and messaging sequence'];
const countries = [['India', 'Mumbai', 'Transit Cloud'], ['United Kingdom', 'London', 'Northline Hosting'], ['United States', 'Ashburn', 'Edge Compute'], ['Germany', 'Frankfurt', 'Metro Transit'], ['Singapore', 'Singapore', 'Harbor Networks'], ['Netherlands', 'Amsterdam', 'Canal Hosting']];
export function incidentMetadata(n: number) { const g = Math.floor((n - 1) / 5); return { id: `INC-2026-${String(g + 1).padStart(4, '0')}`, name: campaignNames[g % 3], description: 'Correlated by shared identity, infrastructure and timing. Determine whether the observations belong to one incident.', correlation: 'Shared identity + infrastructure + time window' }; }
export function generateScenario(n: number, over: Injection = {}): Scenario {
    const r = rng((over.seed ?? 83491) + n * 7919), campaign = n <= 120 && !Object.keys(over).length, g = campaign ? Math.floor((n - 1) / 5) : -1, stage = campaign ? (n - 1) % 5 : 0, cohort = campaign ? g : n + 24;
    const rule = over.category ? rules.find(x => x.id === over.category) ?? rules[0] : campaign ? rules[campaignRules[g % 3][stage]] : rules[(n - 121 + rules.length * 2) % rules.length];
    const u = users.find(x => x.id === over.user) ?? users[(cohort * 7) % 120], baseHost = hosts.find(x => x.id === over.host) ?? hosts.find(x => x.id === u.normalHost)!, secondHost = hosts[120 + (cohort * 11) % 90];
    const host = /sudo/i.test(rule.name) ? (over.host ? baseHost : hosts.filter(h => h.os.startsWith('Ubuntu'))[cohort % 4]) : over.host ? baseHost : rule.family === 'Web' ? hosts.filter(h => h.type === 'Server' && h.os.startsWith('Windows') && h.id.startsWith('WEB'))[cohort % 8] : campaign && stage === 4 && rule.family !== 'Lateral movement' ? secondHost : baseHost;
    const roll = int(r, 0, 9), verdict = campaign ? (g % 11 === 10 ? 'Needs More Investigation' : g % 6 === 5 ? 'Benign Positive' : 'True Positive') : roll < 4 ? 'True Positive' : roll < 6 ? 'False Positive' : roll < 9 ? 'Benign Positive' : 'Needs More Investigation';
    const tp = verdict === 'True Positive', fp = verdict === 'False Positive', bp = verdict === 'Benign Positive', amb = verdict === 'Needs More Investigation', difficulty = over.difficulty ?? (amb ? 'Advanced' : pick(r, ['Beginner', 'Intermediate', 'Advanced']));
    const t = over.timestamp ? Date.parse(over.timestamp) : campaign ? EPOCH - (g + 1) * 1863000 + stage * (171000 + g * 2300) : EPOCH - int(r, 15, 10080) * 60000 - int(r, 0, 59) * 1000, start = t - pick(r, [45, 115, 291, 600, 924, 1800, 2700, 5400]) * 1000;
    const ip = over.ioc && /^\d+\.\d+\.\d+\.\d+$/.test(over.ioc) ? over.ioc : externalIP(cohort % 760), country = countries[cohort % 6];
    const domain = over.ioc && !/^\d+\.\d+\.\d+\.\d+$/.test(over.ioc) ? over.ioc : campaign ? `sync-${cohort}.test` : `${pick(r, ['cdn', 'portal', 'files', 'account', 'sync', 'login', 'update', 'share'])}-${cohort}.test`;
    const url = `https://${domain}/${pick(r, ['verify', 'session', 'documents', 'api/v2', 'portal', 'download'])}/${cohort}`, hash = fauxHash(3481 + cohort * 37 + (campaign ? stage : 0)), sha1 = hash.slice(0, 40), md5 = hash.slice(0, 32);
    const basename = pick(r, ['Quarterly_Review', 'Invoice', 'Benefits', 'Client_Statement', 'Policy_Update', 'Support_Diagnostics']) + '_' + int(r, 100, 9999), file = rule.family === 'Email' ? basename + pick(r, ['.html', '.docm', '.pdf', '.zip']) : basename + pick(r, ['.exe', '.ps1', '.dll', '.js']);
    const process = rule.family === 'Web' ? 'cmd.exe' : rule.family === 'Cloud' ? 'chrome.exe' : /PowerShell/.test(rule.name) ? 'powershell.exe' : pick(r, ['powershell.exe', 'cmd.exe', 'rundll32.exe', 'wscript.exe', 'msiexec.exe']);
    const severity = over.severity ?? (campaign ? pick(r, ['Critical', 'High', 'High'] as const) : pick(r, ['Critical', 'High', 'Medium', 'Medium', 'Low'] as const));
    const id = `ALT-${String(n).padStart(5, '0')}`, incident = campaign ? incidentMetadata(n).id : null, count = fp ? int(r, 1, 3) : pick(r, [3, 7, 16, 28, 50, 97, 184, 462, 1000, 1342]), span = Math.round((t - start) / 1000), approved = bp ? `CHG-${20000 + cohort}` : null;
    const alert: Alert = { id, incident_id: incident, name: rule.name, category: rule.name, family: rule.family, severity, status: 'New', time: iso(t), firstSeen: iso(start), lastSeen: iso(t), source: rule.source, rule_id: rule.id, technique: rule.technique, tactic: rule.tactic, user: u.id, host: host.id, source_ip: ip, destination_ip: host.ip, country: country[0], asn: `AS${64512 + cohort % 100}`, domain, url, file, hash, process_name: process, summary: `${rule.source} observed ${rule.name.toLowerCase()} involving ${u.id} on ${host.id}. Detection window: ${span} seconds. Validate the source records, baseline and activity that followed.` };
    const events: LabEvent[] = [];
    let seq = 0;
    function event(kind: LabEvent['kind'], offset: number, message: string, data: Record<string, any> = {}, opts: Partial<LabEvent> = {}) { const e: LabEvent = { id: `${id}-E${String(++seq).padStart(3, '0')}`, alert_id: id, incident_id: incident, timestamp: iso(t + offset * 1000), kind, source: rule.source, event_id: 0, user: u.id, host: host.id, source_ip: ip, destination_ip: host.ip, domain, hash, process_name: process, message, severity, data, ...opts }; events.push(e); return e; }
    for (let k = 0; k < 3; k++)
        event('auth', -86400 * (k + 1) - int(r, 90, 5400), 'Historical interactive logon', { outcome: 'Success', logonType: 2, authenticationPackage: 'Kerberos', country: u.normalCountry, deviceTrust: 'Managed', mfa: 'Satisfied', sourceWorkstation: baseHost.id, targetUser: u.id, sessionId: `base-${cohort}-${k}` }, { event_id: 4624, source: 'Windows Security', source_ip: baseHost.ip, host: baseHost.id, domain: 'northstar.test', process_name: 'winlogon.exe' });
    event('context', -span - 45, 'Asset and account baseline snapshot', { normalCountry: u.normalCountry, normalHours: u.normalHours, normalEndpoint: baseHost.id, department: u.department, accountRole: u.role, expectedEgress: '10.40.0.0/16' }, { source: 'Asset Inventory' });
    if (bp)
        event('context', -span + 3, 'Change management record matched to activity', { changeId: approved, status: 'Approved', requestor: u.id, approvedBy: u.manager, windowStart: iso(start - 3600000), windowEnd: iso(t + 7200000), assets: [host.id, secondHost.id], purpose: rule.family === 'Network' ? 'Quarterly vulnerability scanning and backup verification' : rule.family === 'Identity' ? 'Travel and corporate VPN egress change' : rule.family === 'Email' ? 'Supplier routing change; recipient requested document' : rule.family === 'Insider' ? 'Month-end archive and legal review' : 'IT maintenance, software deployment and account administration', correlationKey: `ops-${cohort}` }, { source: 'Change Management' });
    if (fp)
        event('context', -span + 12, 'Collector normalization health event', { parserVersion: 'auth-map-3.7', detail: rule.family === 'Email' ? 'Relay rewrote return-path; compare the original message authentication.' : rule.family === 'Network' ? 'Sampling multiplier applied twice; compare raw bytes with the detection aggregate.' : 'Duplicate forwarding and account-alias normalization detected; compare raw record IDs and actual outcomes.', duplicateCopies: int(r, 3, 12), rawRecordCount: count, ticket: `OPS-${9000 + cohort}` }, { source: 'Collector Health' });
    if (amb)
        event('context', -span + 9, 'Telemetry collection gap', { sensor: pick(r, ['Proxy', 'Endpoint Sensor', 'Identity Provider']), gapStart: iso(start), gapEnd: iso(t + 300000), reason: 'Forwarder delivery delay', changeRecords: 'No matching record available at collection time', followUp: 'Request missing telemetry and validate activity with the account owner.' }, { source: 'Collector Health' });
    const failures = ['Identity', 'Lateral movement', 'Cloud', 'Privilege'].includes(rule.family) ? count : tp ? int(r, 1, 14) : int(r, 0, 3);
    if (failures > 0) {
        const samples = Math.min(failures, difficulty === 'Beginner' ? 3 : difficulty === 'Intermediate' ? 5 : 7);
        for (let k = 0; k < samples; k++)
            event('auth', -span + Math.floor(span * (k + 1) / (samples + 2)), k === 0 ? 'Authentication failure cluster' : 'Authentication attempt', { outcome: 'Failure', status: '0xC000006D', subStatus: rule.name.includes('Disabled') ? '0xC0000072' : '0xC000006A', logonType: rule.family === 'Lateral movement' ? 3 : 10, authenticationPackage: rule.name.includes('NTLM') ? 'NTLM' : 'Negotiate', sourceWorkstation: tp ? 'UNREGISTERED' : baseHost.id, targetUser: rule.name.includes('spraying') ? users[(cohort + k) % 120].id : u.id, attemptsRepresented: k === 0 ? failures - samples + 1 : 1, windowSeconds: span, country: bp ? u.normalCountry : country[0], rawRecordId: `SEC-${cohort}-${k}`, collectorDuplicate: fp }, { event_id: 4625, source: 'Windows Security' });
    }
    const success = tp || bp || (!amb && count < 5) || int(r, 0, 1) === 1;
    if (success)
        event('auth', 8, 'Successful authentication', { outcome: 'Success', logonType: rule.family === 'Lateral movement' ? 3 : 10, authenticationPackage: rule.name.includes('NTLM') ? 'NTLM' : 'Kerberos', sourceWorkstation: tp ? 'UNREGISTERED' : baseHost.id, targetUser: u.id, country: bp || fp ? u.normalCountry : country[0], deviceTrust: tp ? 'Unregistered' : bp ? 'Managed' : amb ? 'Unknown' : 'Managed', mfa: rule.name.includes('MFA') ? 'Approved after repeated prompts' : tp ? 'Satisfied by existing session' : 'Satisfied', sessionId: `S-${cohort}-${stage}`, priorFailureCount: failures, tokenIssuer: 'login.northstar.test' }, { event_id: 4624, source: rule.family === 'Cloud' ? 'Cloud Audit' : 'Windows Security' });
    event('auth', 13, 'MFA evaluation', { outcome: amb ? 'Timeout' : success ? 'Approved' : 'Denied', promptCount: rule.name.includes('MFA') ? int(r, 8, 32) : int(r, 1, 3), method: 'Authenticator push', numberMatching: !tp, device: baseHost.id, sessionId: `S-${cohort}-${stage}` }, { source: 'Identity Provider' });
    if (rule.name.includes('Kerberos') || rule.family === 'Lateral movement') {
        event('auth', 24, 'Kerberos ticket request', { outcome: 'Success', serviceName: 'krbtgt', ticketEncryptionType: '0x12', targetUser: u.id, authenticationPackage: 'Kerberos', logonType: 3 }, { event_id: 4768, source: 'Domain Controller' });
        event('auth', 30, 'Service ticket requested', { outcome: 'Success', serviceName: `cifs/${secondHost.id}`, ticketEncryptionType: tp ? '0x17' : '0x12', authenticationPackage: 'Kerberos', logonType: 3 }, { event_id: 4769, source: 'Domain Controller' });
    }
    if (rule.name.includes('NTLM'))
        event('auth', 34, 'Credential validation on domain controller', { outcome: 'Success', authenticationPackage: 'MICROSOFT_AUTHENTICATION_PACKAGE_V1_0', sourceWorkstation: host.id, targetUser: u.id }, { event_id: 4776, source: 'Domain Controller' });
    if (failures > 90)
        event('auth', -5, 'Account lockout policy evaluated', { outcome: tp ? 'Locked' : 'Threshold evaluated', callerComputerName: host.id, failedCount: failures, lockoutThreshold: 50 }, { event_id: 4740, source: 'Domain Controller' });
    const rootPid = 1000 + cohort % 300 * 8, childPid = rootPid + 12, leafPid = rootPid + 28, rootProcess = rule.family === 'Web' ? 'services.exe' : 'explorer.exe';
    event('process', 20, 'Session root process created', { pid: rootPid, ppid: 640, name: rootProcess, path: `C:\\Windows\\${rootProcess}`, commandLine: `C:\\Windows\\${rootProcess}`, signature: 'Microsoft Windows · valid', user: u.id, sha256: fauxHash(41), startTime: iso(t + 20000), connections: [] }, { event_id: 4688, source: 'Endpoint Sensor', process_name: rootProcess, hash: fauxHash(41) });
    const parent = rule.family === 'Email' || tp && rule.family === 'Malware' ? 'winword.exe' : rule.family === 'Web' ? 'w3wp.exe' : bp ? 'CompanyPortal.exe' : rule.family === 'Cloud' ? 'chrome.exe' : 'cmd.exe';
    event('process', 37, 'Child process created', { pid: childPid, ppid: rootPid, name: parent, path: `C:\\Program Files\\${parent}`, commandLine: parent === 'winword.exe' ? `winword.exe C:\\Users\\${u.id}\\Downloads\\${file}` : `${parent} /session ${cohort}`, signature: parent === 'CompanyPortal.exe' ? 'Northstar IT · valid' : 'Microsoft Corporation · valid', user: u.id, sha256: fauxHash(81 + cohort), startTime: iso(t + 37000), connections: [] }, { event_id: 4688, source: 'Endpoint Sensor', process_name: parent, hash: fauxHash(81 + cohort) });
    const command = fp ? `${process} -Version` : bp ? `${process} -File C:\\ProgramData\\Northstar\\Maintenance\\inventory-${cohort}.ps1 -Change ${approved}` : rule.name.includes('Encoded') ? 'powershell.exe -NoProfile -EncodedCommand VwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAiAFMATwBDACAAbABhAGIAIABzAGkAbQB1AGwAYQB0AGkAbwBuACIA' : `${process} -File C:\\Users\\${u.id}\\AppData\\Local\\Temp\\${basename}.ps1 --session ${cohort}`;
    const leaf = event('process', 63, 'Process start recorded', { pid: leafPid, ppid: childPid, name: process, path: fp ? `C:\\Windows\\System32\\${process}` : `C:\\Users\\${u.id}\\AppData\\Local\\Temp\\${process}`, commandLine: command, signature: bp ? 'Northstar IT · valid' : fp ? 'Microsoft Windows · valid' : 'Not present', user: u.id, sha256: hash, startTime: iso(t + 63000), integrity: tp && rule.family === 'Privilege' ? 'High' : 'Medium', connections: fp ? [] : [{ remoteIP: ip, remotePort: 443, domain }], rawBehavior: fp ? 'Version query only; no child file or network activity' : 'File and connection activity recorded' }, { event_id: 4688, source: 'Endpoint Sensor' });
    const dns = event('dns', 78, 'DNS response received', { query: domain, queryType: 'A', answers: [ip], ttl: int(r, 60, 7200), responseCode: 'NOERROR', resolver: '10.40.4.10', labelEntropy: rule.name.includes('entropy') ? 5.8 : 3.2, queryCount: rule.name.includes('DNS') ? int(r, 70, 4800) : int(r, 1, 16), pid: leafPid }, { source: 'DNS Resolver' });
    const bytes = rule.family === 'Insider' || /upload|transfer|archive/i.test(rule.name) ? int(r, 16000000, 790000000) : int(r, 840, 190000), port = rule.family === 'Lateral movement' ? pick(r, [3389, 445, 5985]) : /ports|enumeration/i.test(rule.name) ? pick(r, [22, 80, 135, 139, 445, 3389]) : rule.name.includes('uncommon') ? 8448 : 443;
    const network = event('network', 84, 'Outbound network connection', { sourcePort: int(r, 49152, 65535), destinationPort: port, protocol: port === 443 ? 'TLS' : 'TCP', bytesSent: bytes, bytesReceived: int(r, 1400, 43000), duration: int(r, 3, 840), direction: 'Outbound', firewallAction: fp ? 'Blocked' : 'Allowed', process, pid: leafPid, hostname: host.id, sni: domain, url, proxyCategory: bp ? 'Business application' : 'Uncategorized', httpMethod: bytes > 16000000 ? 'POST' : 'GET', statusCode: fp ? 403 : 200, intervalSeconds: rule.name.includes('interval') ? int(r, 45, 120) : null, connectionCount: int(r, 3, 100), sessionId: `S-${cohort}-${stage}`, sampledBytes: fp ? Math.round(bytes / 10) : bytes }, { source: 'Firewall / Proxy', source_ip: host.ip, destination_ip: ip });
    if (tp || bp)
        for (let k = 0; k < (difficulty === 'Advanced' ? 4 : 2); k++)
            event('network', 130 + k * int(r, 45, 210), 'Follow-on connection', { ...network.data, bytesSent: int(r, 300, 15000), duration: int(r, 1, 35), sourcePort: int(r, 49152, 65535), sequence: k + 2 }, { source: 'Network Flow', source_ip: host.ip, destination_ip: ip });
    const fileEvent = event('file', 105, 'File metadata collected', { file, path: `C:\\Users\\${u.id}\\Downloads\\${file}`, sha256: hash, sha1, md5, size: int(r, 4200, 6400000), signed: bp, signature: bp ? 'Northstar Software Distribution' : 'No verified publisher', origin: url, operation: fp ? 'Read' : rule.name.includes('rename') ? 'Rename / overwrite' : 'Create', filesTouched: rule.name.includes('rename') ? int(r, 200, 8800) : int(r, 1, 8), pid: leafPid }, { source: 'Endpoint Sensor' });
    if (['Email', 'Cloud'].includes(rule.family)) {
        const pass = tp ? n % 3 !== 0 : bp ? n % 3 === 0 : fp ? false : int(r, 0, 1) === 1, sender = tp && pass ? `accounts@vendor-${cohort}.test` : bp ? `service@partner-${cohort}.test` : `billing@${domain}`;
        event('email', -span + 40, 'Message delivered to mailbox', { from: sender, to: u.email, replyTo: tp ? `reply@${domain}` : sender, returnPath: sender, subject: `${pick(r, ['Action requested', 'Document shared', 'Invoice update', 'Account notice'])}: ${basename}`, sendingIP: ip, messageId: `<${cohort}.${stage}.${n}@${domain}>`, spf: pass ? 'Pass' : 'Fail', dkim: pass ? 'Pass' : 'None', dmarc: pass ? 'Pass' : 'Fail', authenticationDomain: sender.split('@')[1], deliveryAction: 'Delivered', body: tp ? 'Please review the updated document. The linked page asks you to sign in again and confirm account details.' : bp ? 'Here is the document requested through the service desk. No credential entry is required.' : fp ? 'Your requested supplier statement is attached. A forwarding relay altered sender authentication.' : 'A shared document is available. Message body collection is incomplete.', urls: [url], attachments: [{ file, sha256: hash, size: fileEvent.data.size }], headers: `From: ${sender}\nTo: ${u.email}\nReply-To: ${tp ? 'reply@' + domain : sender}\nReturn-Path: <${sender}>\nMessage-ID: <${cohort}.${stage}.${n}@${domain}>\nReceived: from relay.${domain} (${ip}) by mail.northstar.test; ${iso(start + 40000)}\nAuthentication-Results: mail.northstar.test; spf=${pass ? 'pass' : 'fail'}; dkim=${pass ? 'pass' : 'none'}; dmarc=${pass ? 'pass' : 'fail'}` }, { source: 'Email Gateway', process_name: 'outlook.exe' });
        if (tp)
            event('context', 120, 'Mail interaction audit', { messageOpened: true, attachmentOpened: rule.family === 'Email', linkClicked: true, credentialFormObserved: true, reportingUser: u.id }, { source: 'Mailbox Audit' });
    }
    if (['Endpoint', 'Malware', 'Privilege', 'Lateral movement'].includes(rule.family)) {
        if (/LSASS|Credential|extraction|memory/i.test(rule.name))
            event('process', 144, 'Process access operation', { pid: leafPid, ppid: childPid, name: process, targetProcess: 'lsass.exe', requestedAccess: tp ? '0x1fffff' : '0x1010', operation: rule.name.includes('memory') ? 'WriteProcessMemory' : 'OpenProcess', handleGranted: !fp, callStack: bp ? 'NorthstarDiagnostics.dll' : 'unmapped module', signature: bp ? 'Approved diagnostics publisher' : 'Not present' }, { event_id: 10, source: 'Sysmon' });
        if (/Run|startup|configuration/i.test(rule.name))
            event('registry', 180, 'Registry value modified', { key: `HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\Sync${cohort}`, value: bp ? 'C:\\Program Files\\Northstar\\Agent.exe' : `C:\\Users\\${u.id}\\AppData\\Local\\Temp\\${file}`, operation: fp ? 'QueryValue' : 'SetValue', pid: leafPid, changeId: approved }, { event_id: 13, source: 'Sysmon' });
        if (/task/i.test(rule.name))
            event('task', 180, 'Scheduled task registration', { name: `\\Northstar\\Update-${cohort}`, action: command, trigger: bp ? 'Weekly maintenance window' : 'At logon', runAs: u.id, enabled: !fp, changeId: approved }, { event_id: 4698, source: 'Windows Security' });
        if (/service/i.test(rule.name) || rule.family === 'Lateral movement')
            event('service', 210, 'Service installation request', { serviceName: `SyncAgent${cohort}`, imagePath: command, startType: bp ? 'Demand start' : 'Auto start', account: 'LocalSystem', installed: !fp, changeId: approved }, { event_id: n % 2 ? 7045 : 4697, source: 'Windows System' });
    }
    if (rule.family === 'Lateral movement' || campaign && stage === 4) {
        event('auth', 244, 'Remote authentication on second endpoint', { outcome: tp || bp ? 'Success' : 'Failure', logonType: port === 3389 ? 10 : 3, authenticationPackage: rule.name.includes('NTLM') ? 'NTLM' : 'Kerberos', targetUser: u.id, sourceWorkstation: baseHost.id, share: 'ADMIN$', approvedChange: approved }, { event_id: tp || bp ? 4624 : 4625, source: 'Windows Security', host: secondHost.id, source_ip: baseHost.ip, destination_ip: secondHost.ip });
        event('network', 252, 'Internal remote session', { sourcePort: int(r, 49000, 63000), destinationPort: port === 443 ? 445 : port, protocol: 'TCP', bytesSent: int(r, 90000, 8000000), bytesReceived: 8000, direction: 'Internal', firewallAction: fp ? 'Blocked' : 'Allowed', duration: int(r, 40, 1200), process: 'mstsc.exe', pid: leafPid, hostname: baseHost.id }, { source: 'Firewall', host: baseHost.id, source_ip: baseHost.ip, destination_ip: secondHost.ip, process_name: 'mstsc.exe' });
    }
    if (rule.family === 'Privilege' && !/sudo/i.test(rule.name)) {
        const eid = rule.name.includes('New') ? 4720 : rule.name.includes('local') ? 4732 : 4728;
        event('auth', 160, 'Privileged identity operation', { outcome: fp ? 'Denied' : 'Success', operation: eid === 4720 ? 'User created' : 'Group membership added', targetUser: `svc.reports${cohort}`, group: 'Administrators', initiator: u.id, changeId: approved, logonType: 3, authenticationPackage: 'Kerberos' }, { event_id: eid, source: 'Windows Security' });
        event('auth', 169, 'Special privileges assigned to session', { outcome: fp ? 'Denied' : 'Success', privileges: ['SeDebugPrivilege', 'SeImpersonatePrivilege'], targetUser: u.id, logonType: 3, authenticationPackage: 'Kerberos' }, { event_id: 4672, source: 'Windows Security' });
    }
    if (rule.family === 'Cloud')
        event('cloud', 150, 'Cloud audit operation', { operation: rule.name.includes('key') ? 'API key authentication' : 'Application consent granted', applicationId: `app-${cohort}`, displayName: `Document Sync ${cohort}`, permissions: tp ? ['Mail.ReadWrite', 'offline_access', 'Files.Read.All'] : ['User.Read'], consentType: 'User', verifiedPublisher: bp, sessionId: `S-${cohort}-${stage}`, resource: 'Graph API (simulated)', result: fp ? 'Denied' : 'Success', changeId: approved }, { source: 'Cloud Audit' });
    if (rule.family === 'Web')
        event('context', -12, 'WAF request inspection', { method: 'GET', uri: rule.name.includes('directory') ? '/files?name=../../config' : rule.name.includes('SQL') ? '/search?q=%27%20OR%201%3D1' : rule.name.includes('markup') ? '/search?q=%3Cscript%3Elab%3C%2Fscript%3E' : '/api/search?cmd=lab-test', userAgent: bp ? 'Northstar-DAST/2.1' : 'Mozilla/5.0 lab-client', wafAction: fp ? 'Block' : 'Log', originStatus: tp ? 200 : 403, responseBytes: tp ? int(r, 1200, 24000) : 324, upstreamExecuted: tp, scannerJob: approved }, { source: 'Web Application Firewall' });
    if (rule.family === 'Insider')
        event('file', 166, 'File access and transfer audit', { operation: rule.name.includes('media') ? 'Removable storage write' : 'Read and archive', file: `department-export-${cohort}.zip`, classification: 'Internal confidential', filesRead: int(r, 100, 2400), bytes, sourcePath: `\\\\FILE-SRV-02\\${u.department}`, destination: rule.name.includes('media') ? 'USB device SIM-USB-' + cohort : url, authorizedRequest: approved, accessRole: u.role, sha256: hash, pid: leafPid }, { source: 'Data Protection' });
    event('auth', 270, 'Explicit credential use audited', { outcome: fp ? 'Denied' : 'Success', targetUser: u.id, processName: process, targetServer: host.id, logonType: 3, authenticationPackage: 'Negotiate' }, { event_id: 4648, source: 'Windows Security' });
    event('auth', 600 + int(r, 1, 800), 'Session ended', { outcome: 'Success', sessionId: `S-${cohort}-${stage}`, targetUser: u.id, logonType: 10, authenticationPackage: 'Kerberos' }, { event_id: 4634, source: 'Windows Security' });
    addCategoryEvidence({ rule, r, tp, bp, fp, amb, u, host, secondHost, baseHost, ip, domain, cohort, leafPid, approved, count, span, process, file, hash }, event);
    event('dns', -30, 'Routine intranet DNS query', { query: 'intranet.northstar.test', answers: ['10.40.4.20'], queryType: 'A', responseCode: 'NOERROR', pid: rootPid }, { source: 'DNS Resolver', domain: 'intranet.northstar.test', source_ip: host.ip, process_name: 'chrome.exe' });
    event('network', 46, 'Routine intranet request', { sourcePort: 53211, destinationPort: 443, protocol: 'TLS', bytesSent: 690, bytesReceived: 4700, duration: 1, direction: 'Internal', firewallAction: 'Allowed', process: 'chrome.exe', hostname: host.id }, { source: 'Proxy', source_ip: host.ip, destination_ip: '10.40.4.20', domain: 'intranet.northstar.test', process_name: 'chrome.exe' });
    // Infrastructure observations are stable across a campaign; provider scores do not establish a verdict.
    const ir = rng(83491 + cohort * 127), signal = tp ? int(ir, 0, 90) : bp ? int(ir, 0, 24) : fp ? int(ir, 10, 61) : int(ir, 25, 58), age = tp && cohort % 3 === 0 ? int(ir, 2, 19) : int(ir, 80, 3400);
    const iocs: IOC[] = [{ value: ip, type: 'IP', observations: { country: country[0], city: country[1], asn: alert.asn, isp: country[2], organization: country[2], reputation: signal > 65 ? 'Elevated provider observations' : signal > 20 ? 'Mixed provider observations' : 'Limited provider observations', riskScore: signal, abuseReports: Math.floor(signal * 1.7), firstSeen: iso(EPOCH - age * 86400000), lastSeen: iso(EPOCH), openPorts: [80, 443], relatedDomains: [domain], providers: { 'Multi-engine detections': `${Math.floor(signal / 5)} / 91`, 'Abuse report confidence': `${signal} / 100`, 'Network categorization': signal > 50 ? 'Hosting / observed automation' : 'Hosting / business services' }, note: 'Synthetic provider observations are evidence, not a verdict.' } }, { value: domain, type: 'Domain', observations: { ageDays: age, registrar: 'Example Registrar (simulated)', created: iso(EPOCH - age * 86400000), expires: iso(EPOCH + (365 - age % 300) * 86400000), riskScore: signal, category: age < 30 ? 'Newly registered' : 'Business / uncategorized', dns: { A: [ip], MX: [`mail.${domain}`], TXT: ['v=spf1 -all'] }, relatedIPs: [ip], lookalikeScore: rule.family === 'Email' ? int(ir, 40, 96) : int(ir, 0, 29), note: 'Registration age does not establish whether an account or site was compromised.' } }, { value: hash, type: 'SHA256', observations: { file, fileType: file.split('.').pop(), size: fileEvent.data.size, detectionScore: `${Math.floor(signal / 4)} / 72`, digitalSignature: bp ? 'Northstar Software Distribution · valid' : 'Not verified', firstSeen: iso(start), threatFamily: signal > 70 ? 'Generic behavior cluster' : 'No consensus', relatedBehavior: [leaf.message, dns.message, network.message], md5, sha1 } }, { value: sha1, type: 'SHA1', observations: { sha256: hash, file, detectionScore: `${Math.floor(signal / 4)} / 72` } }, { value: md5, type: 'MD5', observations: { sha256: hash, file, detectionScore: `${Math.floor(signal / 4)} / 72` } }, { value: url, type: 'URL', observations: { finalURL: tp ? `https://${domain}/session/confirm` : url, redirectChain: tp ? [url, `https://${domain}/redirect`, `https://${domain}/session/confirm`] : [url], domain, riskScore: signal, category: 'Observed web destination', forms: tp ? ['Email', 'Password'] : [], relatedDetections: [rule.name] } }];
    const mail = events.find(e => e.kind === 'email');
    if (mail)
        iocs.push({ value: mail.data.from, type: 'Email', observations: { domain: mail.data.from.split('@')[1], replyTo: mail.data.replyTo, sendingIP: ip, spf: mail.data.spf, dkim: mail.data.dkim, dmarc: mail.data.dmarc, note: 'Evaluate behavior and business context even when authentication passes.' } });
    const scope = (rule.family === 'Lateral movement' || campaign && stage === 4) && tp ? [baseHost.id, secondHost.id] : [host.id];
    const reason = tp ? `${rule.name} is supported by a new session context, execution from a writable location and follow-on activity to ${domain}. ${rule.family === 'Email' ? 'Mail interaction captured a credential form. ' : ''}${scope.length > 1 ? 'Remote authentication links ' + scope.join(' and ') + '. ' : ''}No matching approved change is present. Escalate with the evidence and observed scope.` : bp ? `The behavior occurred, and approved change ${approved}, account baseline and signed maintenance context establish authorization. The rule detected a real authorized activity: a benign positive.` : fp ? 'The collector or normalization context and raw outcomes contradict the aggregate detection. A blocked request or benign version query did not establish the behavior described by the alert. Distinguish detection error from a correctly detected authorized activity.' : 'A collection gap prevents a confident conclusion and authorization has not been established. Request missing records, preserve uncertainty and escalate or monitor with a specific follow-up.';
    const truth: GroundTruth = { verdict, difficulty, reason, scope, expectedAreas: ['timeline', 'ioc', 'identity', 'endpoint', 'network', 'siem', ...(rule.family === 'Email' ? ['email'] : [])], requiredEvidence: [leaf.id, dns.id, network.id, ...events.filter(e => e.kind === 'context').slice(0, 2).map(e => e.id)], dispositions: tp ? ['Escalate to L2', 'Escalate to Incident Response', 'Containment Recommended'] : amb ? ['Escalate to L2', 'Monitor'] : ['Close Alert'] };
    alert.lastSeen = events.reduce((latest, e) => e.timestamp > latest ? e.timestamp : latest, alert.lastSeen);
    return improveScenario({ alert, events, iocs, truth }, (over.seed ?? 83491) + n);
}
