import { fauxHash, int, rng } from './random';
import type { Scenario } from './types';
export const DATASET_VERSION = 3, SEED_PREFIX = 'quality-3-';
export function identityHash(value: string) { let seed = 2166136261; for (const c of value.toLowerCase()) seed = Math.imul(seed ^ c.charCodeAt(0), 16777619); return fauxHash(seed >>> 0); }
export function normalizeIOC(input: string) {
    const s = input.trim().replaceAll('[.]', '.').replace(/^hxxps:/i, 'https:').replace(/^hxxp:/i, 'http:');
    if (/^https?:\/\//i.test(s)) { try { const u = new URL(s); u.hostname = u.hostname.toLowerCase(); return u.href; } catch { return s; } }
    return s.toLowerCase().replace(/\.$/, '');
}
// Versioned IDs retain all previous raw records, investigations and cases.
export function improveScenario(s: Scenario, seed: number): Scenario {
    const a = s.alert, old = a.id, t = Date.parse(a.time), r = rng(seed * 3571 + 229);
    const previous = old.replace(/^ALT-/, 'ALT2-');
    a.id = old.replace(/^ALT-/, 'ALT3-'); a.supersedes = previous; a.priorExerciseIds = [old, previous]; a.datasetVersion = DATASET_VERSION;
    for (const e of s.events) { e.id = e.id.replace(old, a.id); e.alert_id = a.id; }
    const fp = s.truth.verdict === 'False Positive', bp = s.truth.verdict === 'Benign Positive', amb = s.truth.verdict === 'Needs More Investigation';
    const linux = /sudo/i.test(a.name), lateral = a.family === 'Lateral movement';
    a.sequenceProfile = `${a.family.toLowerCase().replaceAll(' ','-')}-${(Math.abs(seed) % 7) + 1}`;
    const starts = s.events.filter(e => e.kind === 'process' && e.event_id === 4688), [root, parent, leaf] = starts;
    const find = (name: string) => s.events.find(e => e.message === name)!;
    const dns = find('DNS response received'), net = find('Outbound network connection'), file = find('File metadata collected'), remote = find('Internal remote session'), remoteAuth = find('Remote authentication on second endpoint');
    const protocol = /RDP/i.test(a.name) ? 'RDP' : /WinRM/i.test(a.name) ? 'WSMan' : /WMI/i.test(a.name) ? 'DCOM / WMI' : 'SMB';
    const port = protocol === 'RDP' ? 3389 : protocol === 'WSMan' ? 5985 : protocol === 'DCOM / WMI' ? 135 : 445;
    const process = linux ? 'sudo' : lateral ? protocol === 'RDP' ? 'mstsc.exe' : protocol === 'WSMan' ? 'powershell.exe' : protocol === 'DCOM / WMI' ? 'wmic.exe' : 'cmd.exe' : a.process_name;
    const ext: Record<string, string> = { 'powershell.exe': '.ps1', 'rundll32.exe': '.dll', 'wscript.exe': '.js', 'msiexec.exe': '.msi', 'cmd.exe': '.cmd', 'chrome.exe': '.html', sudo: '.conf' };
    const oldFile = a.file, attachment = a.family === 'Email' ? { file: oldFile, hash: identityHash(`attachment:${a.id}:${oldFile}`) } : null;
    a.file = oldFile.replace(/\.[^.]+$/, '') + (ext[process] || '.txt'); a.hash = identityHash(`artifact:${a.id}:${a.file}`); a.process_name = process;
    const path = linux ? `/etc/lab-agent/${a.file}` : `${bp ? 'C:\\ProgramData\\Northstar\\Maintenance' : `C:\\Users\\${a.user}\\AppData\\Local\\Temp`}\\${a.file}`, target = remoteAuth?.host || a.host;
    const command = process === 'sudo' ? '/usr/bin/sudo /usr/bin/systemctl status lab-agent' : process === 'powershell.exe' ? lateral ? `powershell.exe -NoProfile -Command "Invoke-Command -ComputerName ${target} -ScriptBlock { Get-Service lab-agent }"` : /Encoded/i.test(a.name) ? 'powershell.exe -NoProfile -EncodedCommand VwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAiAFMATwBDACAAbABhAGIAIABzAGkAbQB1AGwAYQB0AGkAbwBuACIA' : `powershell.exe -NoProfile -File "${path}"` : process === 'rundll32.exe' ? `rundll32.exe "${path}",LabEntry` : process === 'wscript.exe' ? `wscript.exe //B //Nologo "${path}"` : process === 'msiexec.exe' ? `msiexec.exe /i "${path}" /qn` : process === 'chrome.exe' ? `chrome.exe --profile-directory=Default "${a.url}"` : process === 'mstsc.exe' ? `mstsc.exe /v:${target}` : process === 'wmic.exe' ? `wmic.exe /node:${target} process list brief` : lateral ? `cmd.exe /d /c dir "\\\\${target}\\ADMIN$"` : `cmd.exe /d /c "${path}"`;
    const profiles: Record<string, number[]> = { Identity: [15,180], Email: [-160,-5], Endpoint: [-70,-2], Malware: [-90,-4], Network: [-1800,-240], Web: [-30,20], Cloud: [-900,-180], Privilege: [-50,-5], Insider: [-1200,-120], 'Lateral movement': [-150,-12] };
    const at = (e: any, seconds: number) => { e.timestamp = new Date(t + seconds * 1000).toISOString(); if (e.data.startTime) e.data.startTime = e.timestamp; }, bounds = profiles[a.family], leafAt = int(r,bounds[0],bounds[1]);
    at(root,leafAt-int(r,100,1500)); at(parent,leafAt-int(r,4,90)); at(leaf,leafAt); at(file,leafAt-int(r,1,3));
    const dnsAt = a.family === 'Network' ? -int(r,35,200) : leafAt+int(r,2,35); at(dns,dnsAt); at(net,dnsAt+int(r,1,15));
    for(const e of s.events) { if(![root,parent,leaf,file,dns,net].includes(e) && Date.parse(e.timestamp)>=t-50000) at(e,(Date.parse(e.timestamp)-t)/1000+int(r,-8,65)); if(e.message==='Follow-on connection') at(e,(Date.parse(net.timestamp)-t)/1000+(e.data.sequence||2)*int(r,25,180)); if(e.kind==='email') at(e,leafAt-int(r,240,1700)); }
    const imagePath = (name: string) => name === 'sshd' ? '/usr/sbin/sshd' : ['bash','sudo'].includes(name) ? '/usr/bin/'+name : name==='explorer.exe' ? 'C:\\Windows\\explorer.exe' : name==='powershell.exe' ? 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe' : name==='winword.exe' ? 'C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE' : name==='chrome.exe' ? 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' : name==='CompanyPortal.exe' ? 'C:\\Program Files\\Northstar\\CompanyPortal.exe' : name==='w3wp.exe' ? 'C:\\Windows\\System32\\inetsrv\\w3wp.exe' : 'C:\\Windows\\System32\\'+name;
    if(linux) { a.source='Linux Audit'; a.summary=a.summary.replace(/^.*? observed /,'Linux Audit observed '); root.data.name='sshd'; parent.data.name='bash'; }
    else if(a.family==='Email') parent.data.name=/\.docm$/i.test(oldFile)?'winword.exe':'chrome.exe';
    else if(parent.data.name==='winword.exe') parent.data.name='explorer.exe';
    leaf.data.name=process;
    s.iocs=s.iocs.filter(i=>!['SHA256','SHA1','MD5'].includes(i.type));
    for(const p of starts) {
        const name=p.data.name; p.process_name=name; p.data.path=imagePath(name); p.hash=p.data.sha256=identityHash('image:'+p.data.path); p.data.imageSHA256=p.hash;
        p.data.signature=linux?'Distribution package checksum verified':'Publisher signature valid';
        p.data.commandLine=p===leaf?command:name==='winword.exe'?`winword.exe "C:\\Users\\${a.user}\\Downloads\\${oldFile}"`:name==='chrome.exe'?`chrome.exe "${a.url}"`:name==='cmd.exe'?'cmd.exe /d /c ver':name==='bash'?'/usr/bin/bash -l':name==='sshd'?'/usr/sbin/sshd -D':p.data.path;
        p.data.connections=p===leaf&&!fp?[{remoteIP:lateral&&remote?remote.destination_ip:a.source_ip,remotePort:lateral?port:net.data.destinationPort,domain:a.domain}]:[];
        p.data.objectRole='Process image';
        if(p===leaf) { p.data.artifactSHA256=a.hash;p.data.artifactPath=path;p.data.artifactRole='Referenced artifact';p.data.rawBehavior=fp?'Compare raw detector inputs and collector-health discrepancies.':'Correlate the process image, referenced artifact and activity under this PID.'; }
        if(linux) {p.source='Linux Audit';p.event_id=0;}
        s.iocs.push({value:p.hash,type:'SHA256',observations:{file:name,path:p.data.path,sha256:p.hash,identity:'Process image',digitalSignature:p.data.signature,note:'A verified interpreter image can execute an untrusted artifact. The image and artifact are separate objects.'}});
    }
    if(['Network','Cloud','Insider'].includes(a.family)&&seed%2===0) {leaf.data.ppid=root.data.pid;s.events=s.events.filter(e=>e!==parent);}
    for(const e of s.events) {
        const own=starts.find(p=>p.data.pid===e.data.pid);
        if(e.kind!=='process')e.hash='';
        if(e.data.pid===leaf.data.pid&&!starts.includes(e)) {e.process_name=process;if('process'in e.data)e.data.process=process;}
        if(e.kind==='process'&&!starts.includes(e)) {e.hash=own?.hash||leaf.hash;e.data.imageSHA256=e.hash;e.process_name=own?.process_name||process;e.data.name=e.process_name;}
        if(['network','dns'].includes(e.kind)&&own) {e.hash=own.hash;e.data.imageSHA256=e.hash;e.process_name=own.process_name;if('process'in e.data)e.data.process=own.process_name;}
        if(e.kind==='file'||e.data.attachment) {e.hash=e.data.sha256=a.hash;if(e.data.file&&e.data.file!==oldFile)e.hash=e.data.sha256=identityHash(`file:${a.id}:${e.data.file}`);else {if('file'in e.data)e.data.file=a.file;if('path'in e.data)e.data.path=path;}e.data.objectRole=e.data.attachment?'Email attachment':'Observed file';if(e.data.attachment&&attachment){e.data.attachment=attachment.file;e.hash=e.data.sha256=attachment.hash;e.data.objectRole='Email attachment';}}
        if(e.kind==='registry')e.data.value=path;
        if(e.kind==='task')e.data.action=command;
        if(e.kind==='service'){e.data.imagePath='C:\\Program Files\\Northstar\\LabAgent.exe --service';e.data.imageSHA256=identityHash('image:C:\\Program Files\\Northstar\\LabAgent.exe');e.data.commandTemplate='Service ImagePath points to a service binary, not to an installer or script interpreter command.';}
        if(linux&&e.host===a.host&&e.kind==='auth'){e.source='Linux PAM';e.event_id=0;e.data={outcome:e.data.outcome,account:a.user,authenticationMethod:'SSH public key',sessionId:e.data.sessionId,operation:e.message,sourceWorkstation:e.data.sourceWorkstation};}
        if(e.data.processName)e.data.processName=process;
    }
    file.hash=file.data.sha256=a.hash;file.data.file=a.file;file.data.path=path;file.data.objectRole='Referenced artifact';file.process_name=process;file.data.sha1=identityHash('sha1:'+a.hash).slice(0,40);file.data.md5=identityHash('md5:'+a.hash).slice(0,32);
    const email=s.events.find(e=>e.kind==='email');if(email){email.data.attachments=[{file:attachment?.file||a.file,sha256:attachment?.hash||a.hash,size:file.data.size,objectRole:'Email attachment'}];email.data.headers=email.data.headers.replace(/; \d{4}-\d\d-\d\dT[^\n]+/,'; '+email.timestamp);if(attachment)s.iocs.push({value:attachment.hash,type:'SHA256',observations:{file:attachment.file,sha256:attachment.hash,identity:'Email attachment',relatedArtifact:a.hash}});}
    if(lateral&&remote){for(const e of [net,remote,...s.events.filter(e=>e.message==='Follow-on connection')]){e.data.destinationPort=port;e.data.protocol=protocol;e.data.process=process;e.process_name=process;e.data.direction='Internal';e.source_ip=remote.source_ip;e.destination_ip=remote.destination_ip;e.host=remote.host;e.data.hostname=remote.host;}if(remoteAuth){remoteAuth.data.logonType=protocol==='RDP'?10:3;remoteAuth.data.share=protocol==='SMB'?'ADMIN$':undefined;at(remoteAuth,(Date.parse(net.timestamp)-t)/1000+int(r,1,4));at(remote,(Date.parse(remoteAuth.timestamp)-t)/1000+int(r,1,5));}for(const e of s.events.filter(e=>e.message==='Remote protocol evidence')){e.data.protocol=protocol;e.data.port=port;e.data.portContext=protocol==='RDP'?'Default RDP listener (3389) observed; no custom listener is claimed.':`Protocol-native destination port ${port} observed.`;e.data.remoteProcess=protocol==='RDP'?'userinit.exe':protocol==='WSMan'?'wsmprovhost.exe':protocol==='DCOM / WMI'?'WmiPrvSE.exe':'services.exe';}for(const e of s.events.filter(e=>e.kind==='auth'&&e.host===a.host&&[4624,4625].includes(e.event_id)&&!e.message.startsWith('Historical')))e.data.logonType=protocol==='RDP'?10:3;for(const e of s.events.filter(e=>e.event_id===4769))e.data.serviceName=`${protocol==='RDP'?'TERMSRV':protocol==='WSMan'?'HTTP':protocol==='SMB'?'cifs':'HOST'}/${target}`;}
    const lock=s.events.find(e=>e.event_id===4740),success=find('Successful authentication');if(lock?.data.outcome==='Locked'&&success){const unlock={...lock,id:a.id+'-Q001',timestamp:new Date(Date.parse(success.timestamp)-1000).toISOString(),event_id:4767,message:'Account unlocked before new authentication',data:{targetUser:a.user,initiator:'svc.identity-policy',reason:'Configured timed lockout expiry',lockoutRecord:lock.id}};at(lock,(Date.parse(unlock.timestamp)-t)/1000-60);s.events.push(unlock);}
    s.iocs.push({value:a.hash,type:'SHA256',observations:{file:a.file,fileType:a.file.split('.').pop(),sha256:a.hash,md5:file.data.md5,sha1:file.data.sha1,size:file.data.size,identity:'Referenced artifact',imageSHA256:leaf.hash,digitalSignature:bp?'Approved distribution manifest':'Unverified artifact publisher'}},...(['sha1','md5'] as const).map(k=>({value:file.data[k],type:k.toUpperCase(),observations:{sha256:a.hash,file:a.file,identity:'Referenced artifact'}})));
    for(const e of s.events.filter(e=>e.kind==='file'&&e.hash!==a.hash))s.iocs.push({value:e.hash,type:'SHA256',observations:{file:e.data.file,sha256:e.hash,identity:'Observed file'}});
    for(const i of s.iocs)i.value=normalizeIOC(i.value);
    const context=s.events.find(e=>bp?e.data.changeId&&e.kind==='context':fp?e.message.includes('normalization'):amb?e.message.includes('collection gap'):e.message.includes('baseline snapshot'))!;
    const auth=success||s.events.find(e=>e.kind==='auth'&&!e.message.startsWith('Historical'))!,outcome=String(auth.data.outcome||'recorded');
    s.truth.findings=[
        {area:'endpoint',eventId:leaf.id,tokens:[process,String(leaf.data.pid),'image','artifact'],observation:`${process} (PID ${leaf.data.pid}) references ${a.file}; image ${leaf.hash.slice(0,12)}… and artifact ${a.hash.slice(0,12)}… are distinct.`,interpretation:'Correlate ancestry and the artifact; a valid interpreter signature does not establish authorization.',role:'supporting',effect:'supports_verdict'},
        {area:'identity',eventId:auth.id,tokens:[a.user,outcome,'session','authentication','baseline'],observation:`${a.user}: ${auth.message}, outcome ${outcome}, at ${auth.timestamp}.`,interpretation:'Compare the baseline, session and device continuity before attributing activity.',role:'supporting',effect:'supports_verdict'},
        {area:'network',eventId:net.id,tokens:[a.domain,String(net.data.destinationPort),net.destination_ip,'connection','allowed','blocked'],observation:`${net.source_ip} → ${net.destination_ip}:${net.data.destinationPort}, ${net.data.firewallAction}; DNS record ${dns.id} resolves ${a.domain}.`,interpretation:'A connection or reputation score alone does not prove intent; correlate process and destination.',role:'supporting',effect:'supports_verdict'},
        {area:'ioc',eventId:file.id,tokens:[a.hash,a.domain,a.source_ip,'sha256','hash','reputation','artifact','provider'],observation:`${a.file} has SHA256 ${a.hash}; provider observations describe this object separately from the interpreter.`,interpretation:'Keep attachment, payload and image identities separate and corroborate provider observations with telemetry.',role:'supporting',effect:'supports_verdict'},
        {area:'context',eventId:context.id,tokens:bp?[context.data.changeId,'approved','authorization','change']:fp?['normalization','duplicate','raw','collector','threshold']:amb?['gap','missing','uncertain','telemetry']:['baseline',context.data.normalEndpoint,context.data.normalCountry,'authorization','session'].filter(Boolean),observation:`${context.message}: ${bp?context.data.changeId+' covers '+a.host:fp?context.data.detail:amb?context.data.reason:`normal endpoint ${context.data.normalEndpoint}, country ${context.data.normalCountry}`}.`,interpretation:bp?'Match the approved change asset, purpose and time window.':fp?'Raw record and collector discrepancies support detection error. A block alone does not make a false positive.':amb?'The missing source prevents a confident conclusion; identify the collection gap in the handoff.':'Baseline context is a comparison point; validate unusual activity and absence of a matching approved change.',role:fp?'contradicting':'qualifying',effect:fp?'contradicts_detection':amb?'limits_confidence':'qualifies_conclusion'}
    ];
    if(email)s.truth.findings.push({area:'email',eventId:email.id,tokens:[email.data.from,'sender','authentication','attachment','message'],observation:`${email.data.from} → ${email.data.to}; SPF ${email.data.spf}, DKIM ${email.data.dkim}, DMARC ${email.data.dmarc}.`,interpretation:'Evaluate authentication and message behavior together; an authentication pass does not establish safety.',role:'supporting',effect:'supports_verdict'});
    s.truth.requiredEvidence=[leaf.id,dns.id,net.id,context.id,file.id];
    s.truth.reason=`${a.name}: ${bp?'Observed activity is supported by an approved change and matching context.':fp?'Collector discrepancies and raw records do not establish the correlated detection; blocking alone is not the reason for this verdict.':amb?'The documented collection gap leaves the activity unresolved.':'The correlated session, execution and follow-on activity require escalation; no matching authorization was observed.'} Review the cited supporting records and qualifications.`;
    a.firstSeen=s.events.filter(e=>!e.message.startsWith('Historical')).reduce((v,e)=>e.timestamp<v?e.timestamp:v,a.time);a.lastSeen=s.events.reduce((v,e)=>e.timestamp>v?e.timestamp:v,a.time);s.events.sort((x,y)=>x.timestamp.localeCompare(y.timestamp));return s;
}
