import { int } from './random';
import type { LabEvent } from './types';
export function addCategoryEvidence(c: any, add: (kind: LabEvent['kind'], offset: number, message: string, data?: Record<string, any>, opts?: Partial<LabEvent>) => any) {
    const { rule, r, tp, bp, fp, amb, u, host, secondHost, baseHost, ip, domain, cohort, leafPid, approved, count, span, process, file, hash } = c, name = rule.name;
    if (/separated|new country|VPN|anonymizing|baseline/i.test(name) && rule.family === 'Identity') {
        add('auth', -int(r, 120, 900), 'Earlier sign-in from normal network', { outcome: 'Success', country: u.normalCountry, city: 'Bengaluru', deviceId: baseHost.id, sessionId: `travel-${cohort}`, logonType: 10, authenticationPackage: 'SAML', mfa: 'Satisfied', vpnEgress: bp, egressNote: bp ? 'Corporate VPN egress confirmed' : 'No matching gateway declaration', travelRequest: approved }, { event_id: 4624, source: 'VPN Gateway', source_ip: baseHost.ip });
        add('context', 15, 'Geolocation comparison', { distanceKm: int(r, 1200, 12000), elapsedMinutes: int(r, 3, 44), ipGeolocationConfidence: amb ? 'Low' : 'Medium', deviceContinuity: bp || fp ? 'Same managed device' : 'No matching device registration' }, { source: 'Identity Protection' });
    }
    if (/spraying|stuffing/.test(name))
        add('auth', -10, 'Authentication distribution over detection window', { outcome: 'Aggregated', distinctAccounts: fp ? 1 : int(r, 8, 40), attemptCount: count, windowSeconds: span, attemptsPerAccount: name.includes('spraying') ? int(r, 1, 4) : int(r, 4, 23), commonPasswordFingerprint: name.includes('spraying') ? 'Repeated opaque digest' : 'Several opaque digests', passwordValues: 'Not logged', userAgent: bp ? 'Northstar-SSO-HealthCheck' : 'browser-client/' + int(r, 1, 6), approvedTest: approved }, { source: 'Identity Provider' });
    if (/Disabled/.test(name))
        add('context', -50, 'Directory state at detection', { accountEnabled: false, disabledReason: bp ? 'Service retirement under approved change' : 'Leaver workflow completed', cachedServiceConfiguration: bp, changeId: approved }, { source: 'Identity Directory' });
    if (rule.family === 'Email')
        add('context', -22, /QR/.test(name) ? 'QR destination extraction' : /HTML/.test(name) ? 'HTML file reconstruction observation' : /Lookalike/.test(name) ? 'Sender domain comparison' : 'Gateway content analysis', { attachment: file, sha256: hash, extractedURL: `https://${domain}/session/confirm`, qrCodeDetected: /QR/.test(name), htmlBlobCreation: /HTML/.test(name), newReplyToDomain: tp, displayNameSimilarity: /Lookalike/.test(name) ? int(r, 85, 99) : int(r, 10, 55), recipientExpectedMessage: bp, relatedServiceRequest: approved, paymentDetailsChanged: /Payment/.test(name), supplierCallbackRecorded: bp, macroBehavior: /attachment|invoice/i.test(name) ? tp ? 'Document spawned a scripting process' : 'No scripting process after opening' : 'Not applicable', collectionStatus: amb ? 'Partial capture' : 'Complete capture' }, { source: 'Email Content Analysis' });
    if (rule.family === 'Malware') {
        const browser = /Browser/.test(name), mining = /compute/.test(name), rename = /rename/.test(name);
        add('file', 151, 'Endpoint behavioral measurement', { pid: leafPid, process, operation: browser ? 'Open browser Login Data' : rename ? 'Bulk rename and overwrite' : mining ? 'Measure sustained CPU' : /remote access/.test(name) ? 'Register unattended access' : 'Write downloaded executable', path: browser ? `C:\\Users\\${u.id}\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Login Data` : `C:\\Users\\${u.id}\\Documents`, accessGranted: !fp, file, fileCount: rename ? int(r, 300, 12000) : int(r, 1, 28), cpuPercent: mining ? int(r, 82, 99) : int(r, 1, 38), publisher: bp ? 'Approved software catalog' : 'Not verified', approvedSoftware: bp, changeId: approved, sha256: hash }, { source: 'Endpoint Sensor' });
        if (mining)
            add('network', 177, 'Long-lived pool protocol connection', { sourcePort: 55304, destinationPort: 3333, protocol: 'Stratum-like', bytesSent: 18200, bytesReceived: 78100, duration: 1800, direction: 'Outbound', firewallAction: fp ? 'Blocked' : 'Allowed', process, pid: leafPid, hostname: host.id, approvedComputeJob: approved }, { source: 'Network Analytics', source_ip: host.ip, destination_ip: ip });
    }
    if (rule.family === 'Lateral movement')
        add('context', 230, 'Remote protocol evidence', { originEndpoint: baseHost.id, targetEndpoint: secondHost.id, protocol: /WMI/.test(name) ? 'DCOM / WMI' : /WinRM/.test(name) ? 'WSMan' : /RDP/.test(name) ? 'RDP' : /Kerberos/.test(name) ? 'Kerberos' : 'SMB', remoteProcess: /WMI/.test(name) ? 'WmiPrvSE.exe' : /service/.test(name) ? 'services.exe' : 'mstsc.exe', share: /share|SMB/.test(name) ? 'ADMIN$' : null, serviceTicketWithoutTGT: /Kerberos/.test(name) && tp, ntlmWithoutInteractiveSession: /NTLM/.test(name) && tp, authorizationRecord: approved, remoteExecutionObserved: tp || bp }, { source: 'Windows Remote Access' });
    if (rule.family === 'Network') {
        const scan = /ports|enumeration/.test(name), dns = /DNS/.test(name), upload = /upload|transfer|archive/.test(name), beacon = /interval|Repeated/.test(name);
        add(dns ? 'dns' : 'context', 99, scan ? 'Network scan window summary' : dns ? 'DNS behavior sample' : upload ? 'Outbound transfer measurement' : beacon ? 'Connection timing sample' : 'Network protocol classification', { query: domain, queryType: 'A', answers: [ip], queryExamples: dns ? [`a${cohort}b2c3d4e5.${domain}`, `b${cohort}f6a7b8c9.${domain}`, domain] : undefined, uniqueDestinationPorts: scan ? [22, 80, 135, 139, 443, 445, 3389, 5985] : [443], distinctDestinations: scan ? int(r, 8, 94) : 1, observedIntervalsSeconds: beacon ? [61, 60, 62, 59, 61, 60, 63] : undefined, bytesSent: upload ? int(r, 25000000, 860000000) : int(r, 300, 14000), baselineDailyBytes: upload ? int(r, 1000000, 6000000) : 90000, firewallDisposition: fp ? 'Blocked before handshake' : 'Allowed', httpUserAgent: bp ? 'NorthstarBackupAgent/4.2' : process, processOwner: u.id, approvedScanner: scan && bp, backupWindow: upload && bp ? approved : null, feedAgeHours: int(r, 1, 180), sharedHosting: fp || bp, confidence: amb ? 'Insufficient packet context' : 'Metadata captured' }, { source: dns ? 'DNS Analytics' : scan ? 'Firewall Analytics' : 'Proxy Analytics' });
    }
    if (rule.family === 'Privilege' && /sudo/.test(name))
        add('context', 177, 'sudo audit event', { account: u.id, targetUser: 'root', tty: 'pts/2', command: '/usr/bin/systemctl status lab-agent', workingDirectory: '/home/' + u.id, result: fp ? 'DENIED' : 'ACCEPT', approvedChange: approved, initiatorRole: u.role }, { source: 'Linux Audit' });
    if (rule.family === 'Cloud')
        add('cloud', 225, 'Cloud resource access audit', { applicationId: `app-${cohort}`, resource: /mailbox|Cloud session/.test(name) ? 'Mailboxes' : 'Tenant files', operation: /key/.test(name) ? 'ListObjects with API credential' : 'Read messages and modify inbox rule', objectsAccessed: fp ? 0 : int(r, 8, 2100), mailboxRule: tp ? { name: 'Security notifications', action: 'MoveToArchive', externalForward: domain } : null, tokenScopes: tp ? ['Mail.ReadWrite', 'offline_access'] : ['User.Read'], apiKeyId: /key/.test(name) ? `key-sim-${cohort}` : null, permissionsApproved: bp, changeId: approved, result: fp ? 'Access denied' : 'Operation completed' }, { source: 'Cloud Audit' });
}
