import {build} from 'esbuild';
import assert from 'node:assert/strict';
import {writeFileSync,unlinkSync} from 'node:fs';
const bundle=await build({entryPoints:['app/api/lab/route.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'test-d1',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:new URL('./d1-adapter.mjs',import.meta.url).pathname,external:true}))}}]});
const target=new URL('./api-bundle.mjs',import.meta.url);writeFileSync(target,bundle.outputFiles[0].text);
try{
const {GET,POST}=await import(target.href),{sqlite}=await import('./d1-adapter.mjs');
async function get(p,owner='test-analyst'){const r=await GET(new Request('http://lab.test/api/lab?'+new URLSearchParams(p),{headers:{'oai-authenticated-user-id':owner}})),d=await r.json();assert.equal(r.status,200,JSON.stringify(d));return d}
async function post(b,expect=200,owner='test-analyst'){if(b.id){const d=JSON.parse(sqlite.prepare('SELECT data FROM investigations WHERE owner=? AND alert_id=?').get(owner,b.id)?.data||'{}');b={attempt:d.attempt||1,worksheetVersion:d.worksheetVersion||0,...b};if(b.op==='bookmark')b.selected??=true;if(['caseUpdate','caseSync'].includes(b.op))b.caseVersion??=JSON.parse(sqlite.prepare('SELECT data FROM cases WHERE id=? AND owner=?').get(b.caseId,owner)?.data||'{}').revision||0;}const r=await POST(new Request('http://lab.test/api/lab',{method:'POST',headers:{'Content-Type':'application/json','oai-authenticated-user-id':owner},body:JSON.stringify(b)})),d=await r.json();assert.equal(r.status,expect,JSON.stringify(d));return d}
for(let batch=0;batch<24;batch++)await post({op:'initialize',batch});await post({op:'initialize',batch:0});
const w=await get({view:'workspace'});assert.equal(w.alerts.length,600);assert.equal(w.hosts.length,240);assert.equal(w.users.length,120);assert.equal(w.rules.length,91);assert.equal(w.incidents.length,24);assert.ok(w.counts.events>12000);assert.equal(new Set(w.users.map(u=>u.id)).size,120);assert.ok(w.alerts.every(a=>!('truth'in a)&&!('difficulty'in a)));assert.ok(w.alerts.every(a=>w.hosts.some(h=>h.id===a.host)&&w.users.some(u=>u.id===a.user)));
const a=w.alerts.find(a=>a.id==='ALT3-00001'),detail=await get({view:'alert',id:a.id});assert.equal(detail.investigation.feedback,null);assert.ok(detail.events.some(e=>e.event_id===4625));assert.ok(detail.events.some(e=>e.event_id===4624));
await get({view:'ioc',q:a.source_ip,active:a.id});await get({view:'user',id:a.user,active:a.id});await get({view:'host',id:a.host,active:a.id});const siem=await get({view:'events',q:`source_ip = "${a.source_ip}" OR destination_ip = "${a.source_ip}"`,active:a.id});assert.ok(siem.total>0);await get({view:'network',q:`host = "${a.host}"`,active:a.id});const empty=await get({view:'events',q:'source_ip = "1.1.1.1"'});assert.equal(empty.total,0);
const invalid=await GET(new Request('http://lab.test/api/lab?view=events&q='+encodeURIComponent('unrecognized = "value"')));assert.equal(invalid.status,400);
const truth=JSON.parse(sqlite.prepare('SELECT data FROM scenario_truth WHERE alert_id=?').get(a.id).data);for(const eventId of truth.requiredEvidence)await post({op:'bookmark',id:a.id,eventId});
const f=Object.fromEntries(truth.findings.map(f=>[f.area,f]));
const explain=area=>`${f[area].eventId}: ${f[area].observation} ${f[area].interpretation}`;
const wsheet={...detail.investigation.worksheet,verdict:'True Positive',severity:'High',disposition:'Escalate to L2',observedActivity:`Observed execution and session activity: ${explain('endpoint')} ${explain('identity')}`,evidenceReviewed:'Preserved the following linked records and compared their source observations: '+truth.requiredEvidence.join(', ')+'. '+truth.findings.map(f=>f.observation).join(' '),iocFindings:explain('ioc'),endpointFindings:explain('endpoint'),authenticationFindings:explain('identity'),networkFindings:explain('network'),scope:`The supported endpoint scope includes ${truth.scope.join(', ')} as observed in ${f.endpoint.eventId}; related endpoints require additional validation before being declared affected.`,affectedAssets:truth.scope.join(', '),actionTaken:'Simulated endpoint isolation after preserving process and network records.',escalationReason:`Escalate to L2 because ${f.endpoint.eventId} establishes execution correlated with the unusual authenticated session; acquire further endpoint evidence and validate authorization.`,nextStep:'L2 should validate account ownership, scope related endpoints and acquire missing session telemetry.',notes:explain('context')};
await post({op:'submit',id:a.id,worksheet:wsheet},400);await post({op:'save',id:a.id,worksheet:wsheet});const c=await post({op:'case',id:a.id,summary:'Evidence-backed handoff',assigned:'L2 Queue'});await post({op:'caseUpdate',id:a.id,caseId:c.case.id,status:'Resolved'},400);await post({op:'action',id:a.id,action:'Isolate Endpoint',reason:'Preserve the endpoint while related execution is reviewed.',confirmed:true});const finished=await post({op:'submit',id:a.id,worksheet:wsheet});assert.equal(finished.investigation.feedback.score,100,JSON.stringify(finished.investigation.feedback));assert.equal(finished.investigation.status,'Escalated');assert.equal((await get({view:'alert',id:a.id})).investigation.feedback.score,100);await post({op:'bookmark',id:a.id,eventId:truth.requiredEvidence[0]},400);assert.equal((await get({view:'workspace'},'second-analyst')).investigations.length,0);
await import('./regressions.mjs').then(m=>m.regressions({get,post,GET,sqlite,w,wsheet,a,truth}));
const first=await get({view:'events',page:1}),second=await get({view:'events',page:2});assert.ok(first.rows.every(e=>!second.rows.some(x=>x.id===e.id)));const chart=await get({view:'chart'});assert.ok(chart.alerts.length&&chart.events.length);assert.ok(chart.alerts.every(r=>Number.isFinite(Date.parse(r.time))));
const injected=await post({op:'inject',options:{category:'DET-030',seed:1122,ioc:'custom.test',user:a.user,host:a.host,severity:'Medium',difficulty:'Advanced'}});const custom=await get({view:'alert',id:injected.alert.id});assert.ok(custom.events.length>15);assert.equal(custom.alert.domain,'custom.test');assert.equal(custom.alert.user,a.user);await post({op:'inject',options:{ioc:'google.com'}},400);
console.log(JSON.stringify({result:'PASS',alerts:w.alerts.length,events:w.counts.events,endpoints:w.hosts.length,users:w.users.length,rules:w.rules.length,incidents:w.incidents.length,score:finished.investigation.feedback.score,checks:'seed idempotency; hidden truth; identity/IP/process/network pivots; KQL errors and pagination; evidence; draft; case validation; simulated action; submission; persistent retrieval; analyst isolation; chart; injection'},null,2));
}finally{unlinkSync(target)}
