import assert from 'node:assert/strict';
export async function regressions({get,post,GET,sqlite,w,wsheet,a,truth}){
    const id='ALT3-00002';let d=await get({view:'alert',id});assert.equal(d.investigation.worksheet.severity,d.alert.severity);
    const ids=d.events.slice(0,3).map(e=>e.id);await Promise.all(ids.map(eventId=>post({op:'bookmark',id,eventId,selected:true})));d=await get({view:'alert',id});assert.ok(ids.every(x=>d.investigation.bookmarks.includes(x)),'concurrent evidence survives');assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM investigation_bookmarks WHERE owner=? AND alert_id=? AND attempt=?').get('test-analyst',id,1).n,3,'bookmarks are normalized rows rather than a last-writer-wins JSON array');
    await Promise.all([post({op:'bookmark',id,eventId:ids[0],selected:false}),post({op:'save',id,worksheet:{...d.investigation.worksheet,notes:'Draft survives concurrent evidence changes.'}}),get({view:'host',id:d.alert.host,active:id}),get({view:'user',id:d.alert.user,active:id})]);d=await get({view:'alert',id});assert.ok(!d.investigation.bookmarks.includes(ids[0]));assert.ok(ids.slice(1).every(x=>d.investigation.bookmarks.includes(x)));assert.ok(['timeline','identity','endpoint'].every(x=>d.investigation.reviewed.includes(x)));assert.equal(d.investigation.worksheet.notes,'Draft survives concurrent evidence changes.');
    const version=d.investigation.worksheetVersion;await post({op:'save',id,worksheetVersion:version,worksheet:{...d.investigation.worksheet,notes:'The first tab owns the latest saved observation.'}});await post({op:'save',id,worksheetVersion:version,worksheet:{...d.investigation.worksheet,notes:'A stale tab must not replace it.'}},409);
    const filler=Object.fromEntries(Object.keys(wsheet).map(k=>[k,'x'.repeat(80)]));Object.assign(filler,{verdict:'True Positive',severity:'High',disposition:'Monitor',affectedAssets:d.alert.host});await post({op:'submit',id,worksheet:filler},400);
    const gameAlert=w.alerts.find(x=>{const row=sqlite.prepare('SELECT data FROM scenario_truth WHERE alert_id=?').get(x.id);return row&&JSON.parse(row.data).verdict!=='True Positive';}),game=await get({view:'alert',id:gameAlert.id}),gameTruth=JSON.parse(sqlite.prepare('SELECT data FROM scenario_truth WHERE alert_id=?').get(gameAlert.id).data);for(const eventId of gameTruth.requiredEvidence)await post({op:'bookmark',id:gameAlert.id,eventId});await get({view:'ioc',q:game.alert.domain,active:gameAlert.id});await get({view:'host',id:game.alert.host,active:gameAlert.id});await get({view:'user',id:game.alert.user,active:gameAlert.id});await get({view:'network',q:`host = "${game.alert.host}"`,active:gameAlert.id});
    const generic='Analyst reviewed the available security information carefully and documented standard investigation activity for the security operations follow up process.';const gameSheet={...game.investigation.worksheet,verdict:gameTruth.verdict,severity:game.alert.severity,disposition:gameTruth.dispositions[0],observedActivity:generic+' General observations were recorded without scenario facts.',evidenceReviewed:gameTruth.requiredEvidence.join(' ')+' '+generic+' Records were preserved for review.',iocFindings:generic+' Indicator checks were completed.',endpointFindings:generic+' Endpoint checks were completed.',authenticationFindings:generic+' Identity checks were completed.',networkFindings:generic+' Network checks were completed.',scope:`${game.alert.host} ${gameTruth.requiredEvidence[0]} ${generic} Scope was considered.`,affectedAssets:game.alert.host,actionTaken:'No simulated containment action was required during this generic review.',escalationReason:`${gameTruth.requiredEvidence[0]} ${generic} Escalation rationale was documented.`,nextStep:'SOC analyst team should review validate confirm collect and document any remaining telemetry before the next decision.',notes:generic+' Context was considered but no actual scenario observation is stated.'};const gamed=await post({op:'submit',id:gameAlert.id,worksheet:gameSheet});assert.ok(gamed.investigation.feedback.score<100,'generic filler with correct verdict/bookmarks/visits cannot score 100');assert.ok(gamed.investigation.feedback.score<=69,JSON.stringify(gamed.investigation.feedback));
    const lower=await get({view:'ioc',q:a.domain}),upper=await get({view:'ioc',q:a.domain.toUpperCase()}),defanged=await get({view:'ioc',q:a.domain.replace('.', '[.]')});assert.equal(lower.related.length,upper.related.length);assert.equal(lower.related.length,defanged.related.length);assert.ok(lower.related.length>=5);
    assert.ok((await get({view:'ioc',q:a.hash.toUpperCase()})).related.some(x=>x.id===a.id));assert.ok((await get({view:'ioc',q:a.url.replace(a.domain,a.domain.toUpperCase())})).related.some(x=>x.id===a.id));assert.equal((await get({view:'ioc',q:a.url.replace(new URL(a.url).pathname,new URL(a.url).pathname.toUpperCase())})).ioc.type,'Unknown');assert.ok((await get({view:'events',q:`domain = "${a.domain.toUpperCase()}"`})).total>0);
    const processRows=sqlite.prepare("SELECT data FROM events WHERE kind='process'").all().map(x=>JSON.parse(x.data)).filter(e=>e.data.commandLine);assert.ok(processRows.every(e=>!/\s-File\s/i.test(e.data.commandLine)||e.process_name==='powershell.exe'));
    const hashes=new Map();for(const e of processRows){assert.equal(e.hash,e.data.sha256);const names=hashes.get(e.hash)||new Set();names.add(e.process_name.toLowerCase());hashes.set(e.hash,names);}assert.ok([...hashes.values()].every(s=>s.size===1),'an image hash identifies one executable');
    const timing=new Set();for(const alert of w.alerts){const es=sqlite.prepare('SELECT data FROM events WHERE alert_id=?').all(alert.id).map(x=>JSON.parse(x.data)),leaf=es.find(e=>e.message==='Process start recorded'),dns=es.find(e=>e.message==='DNS response received'),net=es.find(e=>e.message==='Outbound network connection'),file=es.find(e=>e.message==='File metadata collected');assert.notEqual(leaf.hash,file.hash);assert.equal(file.hash,alert.hash);assert.equal(leaf.data.artifactSHA256,file.hash);assert.equal(file.data.file,alert.file);assert.ok(Date.parse(file.timestamp)<Date.parse(leaf.timestamp));timing.add([leaf,dns,net].map(e=>Date.parse(e.timestamp)-Date.parse(alert.time)).join(','));for(const p of es.filter(e=>e.kind==='process'&&e.data.commandLine)){const parent=es.find(e=>e.kind==='process'&&e.data.pid===p.data.ppid&&e.host===p.host);if(parent)assert.ok(Date.parse(parent.timestamp)<Date.parse(p.timestamp));}if(/RDP/.test(alert.name)){assert.equal(net.data.destinationPort,3389);assert.equal(es.find(e=>e.message==='Remote authentication on second endpoint').data.logonType,10);}for(const e of es.filter(e=>e.source==='Linux Audit'||e.source==='Linux PAM'))assert.ok(w.hosts.find(h=>h.id===e.host).os.startsWith('Ubuntu'));const t=JSON.parse(sqlite.prepare('SELECT data FROM scenario_truth WHERE alert_id=?').get(alert.id).data);assert.ok(t.requiredEvidence.every(x=>es.some(e=>e.id===x)));assert.ok(t.findings.every(f=>es.some(e=>e.id===f.eventId)));}assert.ok(timing.size>550);
    const current=await get({view:'alert',id:a.id}),caseId=current.case.id;let c=await post({op:'caseUpdate',id:a.id,caseId,status:'Escalated',priority:'Critical',assigned:'L2',summary:'Custom handoff draft',notes:'Preserve this analyst note during handoff updates.'});assert.equal(c.case.slaHours,1);assert.equal(Date.parse(c.case.due_at)-Date.parse(c.case.created_at),3600000);c=await post({op:'caseSync',id:a.id,caseId});assert.ok(c.case.summary.includes(wsheet.observedActivity));assert.equal(c.case.notes,'Preserve this analyst note during handoff updates.');assert.equal(c.case.priority,wsheet.severity);assert.equal(c.case.slaHours,4);assert.equal(Date.parse(c.case.due_at)-Date.parse(c.case.created_at),4*3600000);assert.ok(c.case.slaHistory.length>=2);await post({op:'caseUpdate',id:a.id,caseId,caseVersion:0,status:'Escalated'},409);
    const report=await get({view:'report',id:a.id});assert.ok(report.filename.endsWith('.md'));assert.ok(report.markdown.includes(truth.requiredEvidence[0]));assert.ok(report.markdown.includes('Preserve this analyst note'));assert.ok(report.markdown.includes('Assessment feedback'));
    const next=await post({op:'retry',id:a.id,attempt:1});assert.equal(next.investigation.attempt,2);assert.equal(next.investigation.feedback,null);assert.equal(next.investigation.bookmarks.length,0);assert.equal(next.investigation.worksheet.notes,'');await post({op:'retry',id:a.id,attempt:1},409);await post({op:'save',id:a.id,attempt:1,worksheet:wsheet},409);
    const old=await get({view:'alert',id:a.id,attempt:1});assert.ok(old.readOnly);assert.equal(old.investigation.feedback.score,100);assert.equal(old.investigation.worksheet.notes,wsheet.notes);assert.ok(old.bookmarkedEvents.length>=3);assert.equal(old.case.notes,'Preserve this analyst note during handoff updates.');const fresh=await get({view:'alert',id:a.id});assert.equal(fresh.investigation.feedback,null);assert.equal(fresh.attempts.length,1);assert.ok(!JSON.stringify(fresh.events).includes('groundTruth'));assert.ok(!('findings'in fresh.alert));const hint=await post({op:'hint',id:a.id});assert.equal(hint.level,1);assert.equal(hint.investigation.feedback,null);assert.ok(!hint.hint.includes(truth.verdict));
    const other=await GET(new Request('http://lab.test/api/lab?view=alert&id='+a.id+'&attempt=1',{headers:{'oai-authenticated-user-id':'second-analyst'}}));assert.equal(other.status,200);assert.equal((await other.json()).investigation.feedback,null);const newCase=await post({op:'case',id:a.id});assert.notEqual(newCase.case.id,caseId);assert.equal(newCase.case.attempt,2);
    const zero=await post({op:'inject',options:{category:'DET-030',seed:0}}),again=await post({op:'inject',options:{category:'DET-030',seed:0}});assert.equal(zero.alert.time,again.alert.time);assert.equal(zero.alert.hash,again.alert.hash);assert.notEqual(zero.alert.id,again.alert.id);
    const legacy={...a,id:'ALT-LEGACY',datasetVersion:1};sqlite.prepare('INSERT INTO alerts(id,incident_id,time,severity,family,user,host,source_ip,domain,rule_id,data) SELECT ?,incident_id,time,severity,family,user,host,source_ip,domain,rule_id,? FROM alerts WHERE id=?').run(legacy.id,JSON.stringify(legacy),a.id);const preserved={...old.investigation,alert_id:legacy.id,worksheet:{...wsheet,notes:'Original work is preserved'}};sqlite.prepare('INSERT INTO investigations(owner,alert_id,status,started_at,updated_at,submitted_at,data) VALUES(?,?,?,?,?,?,?)').run('test-analyst',legacy.id,preserved.status,preserved.started_at,preserved.updated_at,preserved.submitted_at,JSON.stringify(preserved));sqlite.prepare('DELETE FROM seed_batches WHERE id=?').run('quality-3-0');await post({op:'initialize',batch:0});const historical=await get({view:'alert',id:legacy.id});assert.equal(historical.investigation.worksheet.notes,'Original work is preserved');assert.ok(historical.readOnly);assert.ok((await get({view:'workspace'})).alerts.every(x=>x.datasetVersion===3));
    console.log('Regression checks PASS: normalized concurrent bookmarks, stale writes, anti-gaming scoring, IOC normalization, command/hash/timing/Linux/RDP accuracy, handoff/SLA history, Markdown, immutable retries, owner isolation, seed zero and legacy work.');
}
