import { all,one,run } from '@/db';
import { decode,seed,inject,getInvestigation,ensureInvestigation,bookmark,saveWorksheet,retry,checkAttempt,mark,hydrateInvestigations,Conflict } from '@/lib/lab/store';
import { parseQuery } from '@/lib/lab/query';
import { rules,severities,verdicts,dispositions } from '@/lib/lab/catalog';
import { emptyWorksheet } from '@/lib/lab/types';
import { validate,score } from '@/lib/lab/scoring';
import { DATASET_VERSION,SEED_PREFIX,normalizeIOC,identityHash } from '@/lib/lab/scenario-quality';
import { handoff,markdownReport,slaHours } from '@/lib/lab/reports';
export const dynamic='force-dynamic';
const response=(d:any,status=200)=>Response.json(d,{status,headers:{'Cache-Control':'no-store'}}),ownerOf=(r:Request)=>r.headers.get('oai-authenticated-user-id')??'local-demo-analyst';
const text=(v:any,n=5000)=>typeof v==='string'?v.slice(0,n):'';
const current=`COALESCE(json_extract(data,'$.datasetVersion'),1)=${DATASET_VERSION}`;
const eventVersion=(v:number,p='e.')=>`${p}alert_id IN (SELECT id FROM alerts WHERE COALESCE(json_extract(data,'$.datasetVersion'),1)=${v})`;
async function alert(id:string){const a=decode(await one('SELECT data FROM alerts WHERE id=?',[id]));if(!a)throw Error('Alert not found');return a;}
async function records(sql:string,args:any[]=[]){return(await all(sql,args)).map(decode);}
async function preserved(ids:string[]){const out=[];for(let n=0;n<ids.length;n+=90)out.push(...await records('SELECT data FROM events WHERE id IN ('+ids.slice(n,n+90).map(()=>'?').join(',')+') ORDER BY timestamp',ids.slice(n,n+90)));return out;}
async function review(owner:string,active:string,area:string,rows:any[]){if(!active)return;const a=await alert(active);if(a.datasetVersion===DATASET_VERSION&&rows.some(e=>e.alert_id===active||e.host===a.host||e.user===a.user||e.incident_id&&e.incident_id===a.incident_id))await mark(owner,active,area);}
async function caseFor(owner:string,id:string,attempt:number){return decode(await one("SELECT data FROM cases WHERE owner=? AND alert_id=? AND COALESCE(json_extract(data,'$.attempt'),1)=?",[owner,id,attempt]));}
async function snapshot(owner:string,a:any,i:any){return{alert:a,investigation:i,events:await records('SELECT data FROM events WHERE alert_id=? ORDER BY timestamp',[a.id]),bookmarkedEvents:await preserved(i.bookmarks),case:await caseFor(owner,a.id,i.attempt||1),actions:await all('SELECT * FROM actions WHERE owner=? AND alert_id=? AND time>=? ORDER BY time',[owner,a.id,i.started_at||new Date().toISOString()])};}
function applySla(c:any,priority:string,now:string,reason:string){
    const previous=c.priority, hours=slaHours(priority), due=new Date(Date.parse(c.created_at||now)+hours*3600000).toISOString();
    c.priority=priority;c.slaHours=hours;c.due_at=due;c.slaPolicy='from_case_creation';c.slaRecalculatedAt=now;
    if(previous!==priority||!Array.isArray(c.slaHistory)||!c.slaHistory.length)c.slaHistory=[...(Array.isArray(c.slaHistory)?c.slaHistory:[]),{time:now,from:previous||null,priority,hours,due_at:due,reason}].slice(-25);
    return c;
}
async function syncCaseFromInvestigation(owner:string,a:any,inv:any,now:string,syncStatus=false){
    const c=await caseFor(owner,a.id,inv.attempt||1);if(!c)return null;const revision=c.revision||0;
    c.summary=handoff(a,inv);c.verdict=inv.worksheet.verdict;c.evidence=inv.bookmarks;if(syncStatus)c.status=inv.status;
    applySla(c,inv.worksheet.severity||a.severity,now,'Investigation handoff sync');c.updated_at=now;c.revision=revision+1;
    const row=await one("UPDATE cases SET status=?,data=? WHERE id=? AND owner=? AND COALESCE(json_extract(data,'$.revision'),0)=? RETURNING data",[c.status,JSON.stringify(c),c.id,owner,revision]);
    if(!row)throw new Conflict('The case changed while syncing the investigation. Reload before retrying.');return decode(row);
}
export async function GET(req:Request){try{
    const p=new URL(req.url).searchParams,v=p.get('view')??'workspace',id=p.get('id')??'',q=p.get('q')??'',active=p.get('active')??'',owner=ownerOf(req),page=Math.max(1,Math.min(100000,Number(p.get('page'))||1));
    if(v==='meta')return response({batches:(await all('SELECT id FROM seed_batches')).map((x:any)=>x.id),seedPrefix:SEED_PREFIX,datasetVersion:DATASET_VERSION});
    if(v==='workspace'){
        const data=await Promise.all(['alerts','users','hosts','detection_rules','incidents'].map(t=>records('SELECT data FROM '+t+(t==='alerts'?' WHERE '+current+' ORDER BY time DESC':''))));
        return response({alerts:data[0],users:data[1],hosts:data[2],rules:data[3],incidents:data[4],datasetVersion:DATASET_VERSION,investigations:await hydrateInvestigations(owner,await records('SELECT data FROM investigations WHERE owner=?',[owner])),attempts:(await records('SELECT data FROM attempts WHERE owner=? ORDER BY alert_id,attempt',[owner])).map(x=>({...x.investigation,archived:true})),cases:await records('SELECT data FROM cases WHERE owner=?',[owner]),actions:await all('SELECT * FROM actions WHERE owner=? ORDER BY time DESC',[owner]),settings:decode(await one('SELECT data FROM settings WHERE owner=?',[owner]))??{analyst:'SOC Analyst L1',timezone:'UTC'},counts:await one(`SELECT (SELECT COUNT(*) FROM events e WHERE ${eventVersion(DATASET_VERSION)}) events,(SELECT COUNT(*) FROM iocs) iocs`)});
    }
    if(v==='alert'||v==='report'){
        const a=await alert(id),requested=Number(p.get('attempt'))||0,archive=requested?decode(await one('SELECT data FROM attempts WHERE owner=? AND alert_id=? AND attempt=?',[owner,id,requested])):null;let s:any;
        if(archive)s={...archive,archived:true,readOnly:true};else{const i=await getInvestigation(owner,id);if(requested&&requested!==i.attempt)throw Error('Attempt not found.');if(v==='alert'&&a.datasetVersion===DATASET_VERSION)await mark(owner,id,'timeline');s=await snapshot(owner,a,await getInvestigation(owner,id));s.readOnly=a.datasetVersion!==DATASET_VERSION;}
        s.legacy=a.datasetVersion!==DATASET_VERSION;s.updatedExercise=s.legacy?(await one("SELECT id FROM alerts WHERE COALESCE(json_extract(data,'$.datasetVersion'),1)=? AND (json_extract(data,'$.supersedes')=? OR EXISTS(SELECT 1 FROM json_each(alerts.data,'$.priorExerciseIds') WHERE value=?))",[DATASET_VERSION,id,id]))?.id:null;s.attempts=(await records('SELECT data FROM attempts WHERE owner=? AND alert_id=? ORDER BY attempt',[owner,id])).map(x=>({attempt:x.investigation.attempt,submitted_at:x.investigation.submitted_at,score:x.investigation.feedback?.score,hintsUsed:x.investigation.hintsUsed||0}));
        if(v==='report')return response({filename:`${s.case?.id||id}-attempt-${s.investigation.attempt||1}.md`,markdown:markdownReport(s.alert,s.investigation,s.bookmarkedEvents,s.case,s.actions)});return response(s);
    }
    const version=active?(await alert(active)).datasetVersion||1:DATASET_VERSION;
    if(v==='host'||v==='user'){const entity=decode(await one('SELECT data FROM '+(v==='host'?'hosts':'users')+' WHERE id=?',[id]));if(!entity)throw Error('Entity not found.');const where=v+'=? AND '+eventVersion(version,'');const rows=await records('SELECT data FROM events WHERE '+where+' ORDER BY timestamp DESC LIMIT 300',[id]);await review(owner,active,v==='host'?'endpoint':'identity',rows);return response({entity,events:rows,total:(await one('SELECT COUNT(*) count FROM events WHERE '+where,[id]))?.count});}
    if(['events','network','email'].includes(v)){
        const parsed=parseQuery(q),where=[parsed.where,eventVersion(version)],args=[...parsed.params],kind=p.get('kind')??(v==='email'?'email':v==='network'?'network':'');if(kind){where.push('e.kind=?');args.push(kind);}
        for(const [key,op]of[['from','>='],['to','<=']])if(p.get(key)){if(!Number.isFinite(Date.parse(p.get(key)!)))throw Error('Invalid time filter.');where.push('e.timestamp'+op+'?');args.push(new Date(p.get(key)!).toISOString());}
        const total=await one('SELECT COUNT(*) count FROM events e WHERE '+where.join(' AND '),args),rows=await records('SELECT e.data FROM events e WHERE '+where.join(' AND ')+' ORDER BY e.timestamp '+parsed.order+',e.id '+parsed.order+' LIMIT ? OFFSET ?',[...args,parsed.limit,(page-1)*parsed.limit]);await review(owner,active,v==='network'?'network':v==='email'?'email':'siem',rows);return response({rows,total:total?.count||0,page,pageSize:parsed.limit});
    }
    if(v==='ioc'){
        const value=normalizeIOC(q),ioc=decode(await one('SELECT data FROM iocs WHERE value=?'+(/^https?:\/\//i.test(value)?'':' COLLATE NOCASE'),[value])),key=ioc?.value||value,digest=ioc?.observations.sha256||key;
        const related=await records(`SELECT data FROM alerts WHERE COALESCE(json_extract(data,'$.datasetVersion'),1)=? AND (source_ip=? COLLATE NOCASE OR domain=? COLLATE NOCASE OR json_extract(data,'$.hash')=? COLLATE NOCASE OR json_extract(data,'$.url')=? OR id IN (SELECT alert_id FROM events WHERE hash=? COLLATE NOCASE OR json_extract(data,'$.data.sha256')=? COLLATE NOCASE OR json_extract(data,'$.data.from')=? COLLATE NOCASE OR EXISTS(SELECT 1 FROM json_each(events.data,'$.data.attachments') WHERE json_extract(value,'$.sha256')=? COLLATE NOCASE)))`,[version,key,key,digest,key,digest,digest,key,digest]);if(active&&related.some(a=>a.id===active))await mark(owner,active,'ioc');return response({ioc:ioc??{value,type:'Unknown',observations:{status:'No simulated intelligence record',note:'No live lookup is performed. An unknown indicator is not evidence of safety.'}},related});
    }
    if(v==='intelligence'){const value=normalizeIOC(q);return response({rows:await records('SELECT data FROM iocs WHERE value LIKE ? COLLATE NOCASE ORDER BY value LIMIT 25 OFFSET ?',['%'+value+'%',(page-1)*25]),total:(await one('SELECT COUNT(*) count FROM iocs WHERE value LIKE ? COLLATE NOCASE',['%'+value+'%']))?.count||0,page,pageSize:25});}
    if(v==='chart'){const to=(await one('SELECT MAX(time) time FROM alerts WHERE '+current))?.time;if(!to)return response({referenceTime:null,alerts:[],events:[]});const from=new Date(Date.parse(to)-86400000).toISOString();return response({referenceTime:to,alerts:await all("SELECT substr(time,1,13)||':00:00Z' time,severity,COUNT(*) value FROM alerts WHERE time>=? AND "+current+' GROUP BY substr(time,1,13),severity ORDER BY time',[from]),events:await all("SELECT substr(timestamp,1,13)||':00:00Z' time,kind,COUNT(*) value FROM events e WHERE timestamp>=? AND "+eventVersion(version)+' GROUP BY substr(timestamp,1,13),kind ORDER BY time',[from])});}
    return response({error:'Unknown view'},404);
}catch(e:any){return response({error:e instanceof Error?e.message:'Unable to load the lab.'},e.status||400);}}
export async function POST(req:Request){try{
    const body=await req.text();if(body.length>100000)throw Error('Request is too large.');const b=JSON.parse(body),op=text(b.op,50),owner=ownerOf(req),now=new Date().toISOString();
    if(op==='initialize'){await seed(Number(b.batch));return response({ok:true});}
    if(op==='settings'){const settings={analyst:text(b.settings?.analyst,80)||'SOC Analyst L1',timezone:['UTC','Asia/Kolkata','Europe/London','America/New_York'].includes(b.settings?.timezone)?b.settings.timezone:'UTC'};await run('INSERT INTO settings(owner,data) VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data',[owner,JSON.stringify(settings)]);return response({settings});}
    if(op==='inject'){
        const o=b.options||{},rule=o.category?rules.find(r=>r.id===o.category):null;if(o.category&&!rule)throw Error('Choose a valid detection.');if(o.severity&&!severities.includes(o.severity))throw Error('Invalid severity.');if(o.difficulty&&!['Beginner','Intermediate','Advanced'].includes(o.difficulty))throw Error('Invalid difficulty.');if(o.user&&!await one('SELECT id FROM users WHERE id=?',[o.user]))throw Error('Choose an existing user.');const h=o.host?decode(await one('SELECT data FROM hosts WHERE id=?',[o.host])):null;if(o.host&&!h)throw Error('Choose an existing endpoint.');if(rule&&h&&/sudo/i.test(rule.name)!==h.os.startsWith('Ubuntu'))throw Error('Choose an endpoint with the operating system required by this detection.');if(o.timestamp&&!Number.isFinite(Date.parse(o.timestamp)))throw Error('Invalid timestamp.');if(o.ioc&&!/^(?:(?:192\.0\.2|198\.51\.100|203\.0\.113)\.(?:[1-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-4])|[a-z0-9][a-z0-9.-]*\.test)$/.test(normalizeIOC(o.ioc)))throw Error('Use a .test domain or TEST-NET address.');if(o.seed!==undefined&&o.seed!==''&&!Number.isFinite(Number(o.seed)))throw Error('Seed must be a finite number.');const opts:any={seed:o.seed===undefined||o.seed===''?Date.now()%1000000:Number(o.seed)};for(const k of['category','severity','user','host','ioc','timestamp','difficulty'])if(o[k])opts[k]=k==='ioc'?normalizeIOC(text(o[k],250)):text(o[k],250);return response({alert:await inject(opts)});
    }
    const id=text(b.id,100),a=await alert(id),i=await getInvestigation(owner,id);
    if(!['case','caseUpdate','caseSync'].includes(op)&&a.datasetVersion!==DATASET_VERSION)throw Error('This earlier exercise is preserved for reference. Open its corrected exercise to continue training.');
    if(['bookmark','save','submit','retry','hint','action','case'].includes(op))checkAttempt(b,i);i.started_at||=now;
    if(op==='bookmark'){if(i.submitted_at)throw Error('Submitted assessments are read-only.');const eid=text(b.eventId,100),e=decode(await one('SELECT data FROM events WHERE id=?',[eid]));if(!e||!(e.alert_id===id||e.user===a.user||e.host===a.host||e.incident_id&&e.incident_id===a.incident_id)||(await alert(e.alert_id)).datasetVersion!==a.datasetVersion)throw Error('Select a related evidence record from this dataset.');if(typeof b.selected!=='boolean')throw Error('Specify whether to preserve or remove this record.');return response({investigation:await bookmark(owner,id,eid,b.selected,i.attempt!)});}
    if(op==='hint'){if(i.submitted_at)throw Error('Use the feedback after submission.');await ensureInvestigation(owner,id);const row=await one("UPDATE investigations SET data=json_set(data,'$.hintsUsed',MIN(3,COALESCE(json_extract(data,'$.hintsUsed'),0)+1),'$.revision',COALESCE(json_extract(data,'$.revision'),0)+1) WHERE owner=? AND alert_id=? AND submitted_at IS NULL AND COALESCE(json_extract(data,'$.attempt'),1)=? RETURNING data",[owner,id,i.attempt!]);if(!row)throw new Conflict('The attempt changed. Reload to continue.');const inv=decode(row),hints=['Compare the detected session with historical sign-ins. Record source, device and time before forming a verdict.','Trace process ancestry and the referenced artifact, then inspect DNS and network records. Keep the process image hash separate from the artifact hash.','Check change management and collector-health records. Match asset, purpose and time; document uncertainty and a specific next step.'];return response({level:inv.hintsUsed,hint:hints[inv.hintsUsed-1],investigation:inv});}
    if(op==='retry')return response({investigation:await retry(owner,i,await snapshot(owner,a,i))});
    if(op==='save'||op==='submit'){
        if(i.submitted_at){if(op==='submit')return response({investigation:i});throw Error('Submitted assessments are read-only.');}if(!Number.isInteger(b.worksheetVersion)||b.worksheetVersion!==i.worksheetVersion)throw new Conflict('A newer worksheet is saved. Your local draft is preserved; reload and compare before saving.');const w={...emptyWorksheet};for(const k of Object.keys(w))(w as any)[k]=text(b.worksheet?.[k]);if(w.verdict&&!verdicts.includes(w.verdict))throw Error('Invalid verdict.');if(w.disposition&&!dispositions.includes(w.disposition))throw Error('Invalid disposition.');if(!severities.includes(w.severity))w.severity=a.severity;i.worksheet=w;i.status=['Assigned','Investigating','Pending'].includes(b.status)?b.status:'Investigating';i.updated_at=now;
        if(op==='submit'){validate(w,i.bookmarks);if(w.disposition.startsWith('Escalate')&&!await caseFor(owner,id,i.attempt!))throw Error('Create a case before submitting an escalation.');i.feedback=score(i,decode(await one('SELECT data FROM scenario_truth WHERE alert_id=?',[id])));i.submitted_at=now;i.status=w.disposition==='Close Alert'?'Closed':w.disposition==='Monitor'?'Pending':'Escalated';}
        const saved=await saveWorksheet(owner,i,b.worksheetVersion,op==='submit');if(op==='submit')await syncCaseFromInvestigation(owner,a,saved,now,true);return response({investigation:saved});
    }
    if(op==='case'){const existing=await caseFor(owner,id,i.attempt!);if(existing)return response({case:existing});const priority=i.worksheet.severity||a.severity,hours=slaHours(priority),due_at=new Date(Date.parse(now)+hours*3600000).toISOString(),c={id:`CASE-${id}-${i.attempt}-${identityHash(owner).slice(0,8).toUpperCase()}`,alert_id:id,incident_id:a.incident_id,attempt:i.attempt,revision:0,priority,status:'New',assigned:text(b.assigned,80)||'SOC Analyst L1',created_at:now,updated_at:now,slaHours:hours,due_at,slaPolicy:'from_case_creation',slaRecalculatedAt:now,slaHistory:[{time:now,from:null,priority,hours,due_at,reason:'Case created'}],summary:handoff(a,i),notes:'',verdict:i.worksheet.verdict,evidence:i.bookmarks};await run('INSERT OR IGNORE INTO cases(id,owner,alert_id,status,data) VALUES(?,?,?,?,?)',[c.id,owner,id,c.status,JSON.stringify(c)]);return response({case:await caseFor(owner,id,i.attempt!)});}
    if(op==='caseUpdate'||op==='caseSync'){
        const c=decode(await one('SELECT data FROM cases WHERE id=? AND owner=? AND alert_id=?',[text(b.caseId,100),owner,id]));if(!c)throw Error('Case not found.');const revision=c.revision||0;if(b.caseVersion!==revision)throw new Conflict('This case changed in another tab. Your draft is preserved; reload to compare.');const attempt=c.attempt||1,old=attempt!==i.attempt?decode(await one('SELECT data FROM attempts WHERE owner=? AND alert_id=? AND attempt=?',[owner,id,attempt])):null,inv=old?.investigation||i;
        if(op==='caseSync'){c.summary=handoff(old?.alert||a,inv);c.verdict=inv.worksheet.verdict;c.evidence=inv.bookmarks;applySla(c,inv.worksheet.severity||(old?.alert||a).severity,now,'Investigation handoff sync');}else{if(!['New','Assigned','Investigating','Pending','Escalated','Resolved','Closed'].includes(b.status))throw Error('Invalid case status.');if(['Closed','Resolved'].includes(b.status)&&!inv.submitted_at)throw Error('Submit the assessment before closing its case.');c.status=b.status;c.assigned=text(b.assigned,80)||c.assigned;const requestedPriority=severities.includes(b.priority)?b.priority:c.priority;applySla(c,requestedPriority,now,requestedPriority!==c.priority?'Case priority changed':'Case updated');c.summary=text(b.summary,16000);c.notes=text(b.notes);}
        if(!c.slaPolicy)applySla(c,c.priority,now,'SLA policy migration');c.updated_at=now;c.revision=revision+1;const row=await one("UPDATE cases SET status=?,data=? WHERE id=? AND owner=? AND COALESCE(json_extract(data,'$.revision'),0)=? RETURNING data",[c.status,JSON.stringify(c),c.id,owner,revision]);if(!row)throw new Conflict('The case changed while saving. Reload before retrying.');return response({case:decode(row)});
    }
    if(op==='action'){if(i.submitted_at)throw Error('Start a new attempt to record more response actions.');const targets:Record<string,string>={'Isolate Endpoint':a.host,'Disable User':a.user,'Reset Password':a.user,'Block IP':a.source_ip,'Block Domain':a.domain,'Quarantine File':a.hash,'Revoke Sessions':a.user,'Quarantine Email':a.id},action=text(b.action,80),reason=text(b.reason,1000);if(!targets[action]||b.confirmed!==true||reason.trim().length<15)throw Error('Choose an action, record a reason and confirm.');if(action==='Quarantine Email'&&!await one("SELECT id FROM events WHERE alert_id=? AND kind='email'",[id]))throw Error('No message is linked to this alert.');await ensureInvestigation(owner,id);const result:any=await run("INSERT INTO actions(id,owner,alert_id,target,action,time,reason) SELECT ?,owner,alert_id,?,?,?,? FROM investigations WHERE owner=? AND alert_id=? AND submitted_at IS NULL AND COALESCE(json_extract(data,'$.attempt'),1)=?",[crypto.randomUUID(),targets[action],action,now,reason,owner,id,i.attempt]);if(!(result?.meta?.changes??result?.changes))throw new Conflict('The attempt changed before the action was recorded.');return response({ok:true});}
    return response({error:'Unknown operation'},400);
}catch(e:any){return response({error:e instanceof Error?e.message:'Unable to save changes. Your input is preserved.'},e.status||400);}}
