'use client';
import {useEffect,useRef,useState} from 'react';
import {Textarea} from '@/components/ui/textarea';
import {severities} from '@/lib/lab/catalog';
import {slaHours} from '@/lib/lab/reports';
import {useLab,Button,Input,Heading,Panel,Badge,Pick,GridTable,Pivot,KeyValues,When,mutate,request,toast,download,downloadText,copy} from './common';
const fields=(c:any)=>JSON.stringify({status:c.status,assigned:c.assigned,priority:c.priority,summary:c.summary,notes:c.notes});
export function CasePage(){
    const {workspace:w,params,nav,refresh,registerFlush}=useLab(),c=w.cases.find((x:any)=>x.id===params.id),[draft,D]=useState<any>(c||{}),[busy,B]=useState(false),[error,E]=useState(''),[saved,S]=useState(c?.updated_at||'');
    const ref=useRef(draft),last=useRef(fields(c||{})),version=useRef(c?.revision||0),queue=useRef<Promise<any>>(Promise.resolve()),ready=useRef(false),conflict=useRef('');ref.current=draft;const key='sentinel-case-draft-'+params.id;
    useEffect(()=>{if(!c)return;let local:any;try{local=JSON.parse(localStorage.getItem(key)||'null');}catch{}if(local){D(local.draft);if(local.caseVersion!==(c.revision||0)){conflict.current='A newer case is saved. Export this draft, then load the saved case to compare.';E(conflict.current);}}ready.current=true;},[params.id]);
    const flush=async()=>{queue.current=queue.current.catch(()=>{}).then(async()=>{if(!c||!ready.current||fields(ref.current)===last.current)return;if(conflict.current)throw Error(conflict.current);const snapshot={...ref.current},serialized=fields(snapshot);try{const r=await mutate({...snapshot,op:'caseUpdate',id:c.alert_id,caseId:c.id,caseVersion:version.current});version.current=r.case.revision;last.current=serialized;S(r.case.updated_at);E('');if(fields(ref.current)===serialized){D(r.case);localStorage.removeItem(key);}}catch(e:any){E(e.message);if(e.status===409)conflict.current=e.message;throw e;}});return queue.current;};
    const fn=useRef(flush);fn.current=flush;useEffect(()=>registerFlush(()=>fn.current()),[params.id,registerFlush]);
    useEffect(()=>{if(!c||!ready.current||fields(draft)===last.current)return;try{localStorage.setItem(key,JSON.stringify({draft,caseVersion:version.current}));}catch{E('Browser draft storage is unavailable. Save before leaving.');}if(conflict.current)return;const timer=setTimeout(()=>fn.current().catch(()=>{}),1000);return()=>clearTimeout(timer);},[draft]);
    useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(c&&fields(ref.current)!==last.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[c?.id]);
    async function perform(fn:()=>Promise<void>){B(true);try{await fn();}catch(e:any){toast.error(e.message);}finally{B(false);}}
    if(!c)return <><Heading title="Case management" description="Evidence-backed handoffs with ownership, priority and SLA tracking."/><Panel><GridTable rows={w.cases} empty="No cases yet. Create one from an investigation." columns={[{key:'id',label:'Case',render:(c:any)=><Pivot view="cases" id={c.id}/>},{key:'alert_id',label:'Detection',render:(c:any)=><Pivot view="alert" id={c.alert_id}/>},{key:'attempt',label:'Attempt',render:(c:any)=>c.attempt||1},{key:'priority',label:'Priority',render:(c:any)=><Badge>{c.priority}</Badge>},{key:'status',label:'Status',render:(c:any)=><Badge>{c.status}</Badge>},{key:'assigned',label:'Assigned to'},{key:'sla',label:'SLA',render:(c:any)=>{const min=Math.round(((c.due_at?Date.parse(c.due_at):Date.parse(c.created_at)+c.slaHours*3600000)-Date.now())/60000);return ['Closed','Resolved'].includes(c.status)?'Complete':min<0?Math.abs(min)+' min overdue':min+' min remaining';}}]}/></Panel></>;
    return <><Heading title={c.id} description={`Linked investigation ${c.alert_id} · attempt ${c.attempt||1}`}><Button variant="outline" onClick={()=>nav('alert',{id:c.alert_id,attempt:String(c.attempt||1)})}>Open investigation</Button><Button variant="outline" onClick={()=>perform(async()=>{await flush();const r=await request({view:'report',id:c.alert_id,attempt:c.attempt||1});downloadText(r.filename,r.markdown);})}>Download Markdown report</Button><Button variant="outline" onClick={()=>download(c.id+'.json',draft)}>Export case JSON</Button></Heading>
    {error&&<div className="note" role="alert"><p>{error}</p><div className="toolbar"><Button variant="outline" onClick={()=>download(c.id+'-local-draft.json',draft)}>Export local draft</Button><Button variant="outline" onClick={()=>perform(async()=>{const latest=(await request({view:'workspace'})).cases.find((x:any)=>x.id===c.id);localStorage.setItem(key+'-recovered',JSON.stringify(ref.current));localStorage.removeItem(key);conflict.current='';E('');version.current=latest.revision||0;last.current=fields(latest);D(latest);await refresh();})}>Load saved case</Button></div></div>}
    <Panel title="Case handoff" detail={error?'Draft needs attention':fields(draft)!==last.current?'Saving draft…':saved?'Saved '+new Date(saved).toLocaleTimeString():'Draft'}><div className="form-grid"><Pick label="Case status" value={draft.status} options={['New','Assigned','Investigating','Pending','Escalated','Resolved','Closed']} onChange={v=>D({...draft,status:v})}/><Pick label="Priority" value={draft.priority} options={severities} onChange={v=>D({...draft,priority:v})}/><label className="field"><span>Assigned analyst</span><Input aria-label="Assigned analyst" value={draft.assigned||''} onChange={e=>D({...draft,assigned:e.target.value})}/></label><KeyValues data={{created:c.created_at,updated:saved,SLA:(draft.slaHours??slaHours(draft.priority))+' hours from creation',due:draft.due_at||new Date(Date.parse(c.created_at)+slaHours(draft.priority)*3600000).toISOString(),verdict:draft.verdict||'Not submitted'}}/></div><p className="text-xs">Priority policy: Critical 1h · High 4h · Medium 24h · Low 48h. The explicit SLA policy is <strong>from original case creation</strong>; changing priority or refreshing the investigation handoff recalculates the deadline and records the change.</p>{Array.isArray(draft.slaHistory)&&draft.slaHistory.length>0&&<details className="mt-3"><summary>SLA history ({draft.slaHistory.length})</summary><div className="space-y-2 mt-2">{draft.slaHistory.map((x:any,n:number)=><div className="note" key={n}><When value={x.time}/> · {x.from?x.from+' → ':''}<strong>{x.priority}</strong> · {x.hours}h · due <When value={x.due_at}/>{x.reason?' · '+x.reason:''}</div>)}</div></details>}
    <label className="field mt-5"><span>Generated handoff / case summary</span><Textarea aria-label="Case summary" className="min-h-[220px]" value={draft.summary||''} onChange={e=>D({...draft,summary:e.target.value})}/></label><label className="field mt-5"><span>Additional case notes</span><Textarea aria-label="Case notes" value={draft.notes||''} onChange={e=>D({...draft,notes:e.target.value})}/></label><div className="toolbar mt-4"><Button disabled={busy} onClick={()=>perform(async()=>{await flush();await refresh();toast.success('Case updated');})}>Save case</Button><Button variant="outline" disabled={busy} onClick={()=>perform(async()=>{await flush();const r=await mutate({op:'caseSync',id:c.alert_id,caseId:c.id,caseVersion:version.current});D(r.case);ref.current=r.case;version.current=r.case.revision;last.current=fields(r.case);S(r.case.updated_at);await refresh();toast.success('Handoff, priority and SLA refreshed; additional notes preserved');})}>Update handoff from investigation</Button><Button variant="outline" onClick={()=>copy(draft.summary)}>Copy summary</Button></div><p className="text-xs">Updating the handoff replaces its generated summary, verdict, evidence and priority with the latest investigation. SLA is recalculated from original case creation; additional case notes are preserved.</p><h3>Preserved record IDs</h3><pre>{(draft.evidence||[]).join('\n')||'Bookmark evidence in the linked alert.'}</pre></Panel></>;
}
