'use client';
import { useEffect,useRef,useState } from 'react';
import { Textarea } from '@/components/ui/textarea';
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { emptyWorksheet } from '@/lib/lab/types';
import { worksheetFields,verdicts,dispositions,severities } from '@/lib/lab/catalog';
import { handoff,markdownReport } from '@/lib/lab/reports';
import { RelationshipView } from './relationships';
import { useLab,useApi,Button,Heading,Panel,Badge,Pick,Pivot,When,AlertRows,Events,KeyValues,Loading,mutate,request,toast,copy,download,downloadText } from './common';
export function Investigation(){
    const {params,workspace,refresh,registerFlush,nav,inspect}=useLab(),id=params.id,{data,error}=useApi({view:'alert',id,attempt:params.attempt});
    const [w,W]=useState<any>({...emptyWorksheet}),[tab,T]=useState(params.tab||'timeline'),[busy,B]=useState(false),[saved,S]=useState(''),[confirm,C]=useState(false),[respond,R]=useState(false),[action,A]=useState('Isolate Endpoint'),[reason,N]=useState(''),[status,ST]=useState('Investigating'),[saveError,SE]=useState(''),[hint,H]=useState('');
    const init=useRef(''),draft=useRef(w),statusRef=useRef(status),last=useRef(''),lastStatus=useRef('Investigating'),version=useRef(0),attempt=useRef(1),locked=useRef(false),queue=useRef<Promise<any>>(Promise.resolve()),conflict=useRef('');draft.current=w;statusRef.current=status;
    const localKey=()=>`sentinel-draft-${id}-attempt-${attempt.current}`;
    const adopt=(inv:any,local:any=null)=>{attempt.current=inv.attempt||1;version.current=inv.worksheetVersion||0;last.current=JSON.stringify(inv.worksheet);lastStatus.current=inv.status==='New'?'Investigating':inv.status;draft.current=local?.worksheet||inv.worksheet;statusRef.current=local?.status||lastStatus.current;W(draft.current);ST(statusRef.current);S(inv.updated_at);};
    useEffect(()=>{if(!data)return;const inv=data.investigation,key=`${id}:${inv.attempt||1}:${data.archived?'archive':'current'}`;locked.current=!!inv.submitted_at||data.readOnly;if(init.current===key){if(JSON.stringify(draft.current)===last.current&&(inv.worksheetVersion||0)!==version.current)adopt(inv);return;}init.current=key;attempt.current=inv.attempt||1;let local:any=null;try{local=JSON.parse(localStorage.getItem(localKey())||'null');}catch{}if(locked.current)local=null;adopt(inv,local);const msg=local&&local.worksheetVersion!==(inv.worksheetVersion||0)?'A local draft and a newer saved worksheet exist. Export the local draft, then load the saved worksheet to compare.':'';conflict.current=msg;SE(msg);},[data,id]);
    const flush=async()=>{queue.current=queue.current.catch(()=>{}).then(async()=>{if(!init.current||locked.current)return;if(conflict.current)throw Error(conflict.current);const worksheet={...draft.current},serialized=JSON.stringify(worksheet),s=statusRef.current;if(serialized===last.current&&s===lastStatus.current)return;try{const r=await mutate({op:'save',id,attempt:attempt.current,worksheetVersion:version.current,worksheet,status:s});version.current=r.investigation.worksheetVersion;last.current=serialized;lastStatus.current=s;S(r.investigation.updated_at);SE('');if(JSON.stringify(draft.current)===serialized)localStorage.removeItem(localKey());}catch(e:any){if(e.status===409)conflict.current=e.message;SE(e.message);throw e;}});return queue.current;};
    const fn=useRef(flush);fn.current=flush;useEffect(()=>registerFlush(()=>fn.current()),[id,registerFlush]);
    useEffect(()=>{if(!init.current||locked.current||JSON.stringify(w)===last.current&&status===lastStatus.current)return;try{localStorage.setItem(localKey(),JSON.stringify({worksheet:w,worksheetVersion:version.current,status}));}catch{SE('Browser draft storage is unavailable. Save before leaving this page.');}if(conflict.current)return;const timer=setTimeout(()=>fn.current().catch(()=>{}),1000);return()=>clearTimeout(timer);},[w,id,status]);
    useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(!locked.current&&JSON.stringify(draft.current)!==last.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[]);
    async function perform(fn:()=>Promise<void>){B(true);try{await fn();}catch(e:any){toast.error(e.message);}finally{B(false);}}
    if(!data)return <Loading error={error}/>;
    const a=data.alert,inv=data.investigation,readOnly=!!inv.submitted_at||data.readOnly,c=data.case,actions=data.actions||[],linked=workspace.alerts.filter((x:any)=>x.id!==id&&(x.incident_id&&x.incident_id===a.incident_id||x.user===a.user||x.host===a.host||x.source_ip===a.source_ip||x.domain===a.domain));
    const liveInv=()=>({...inv,attempt:attempt.current,worksheet:draft.current});
    async function createCase(){await flush();const r=await mutate({op:'case',id,attempt:attempt.current,assigned:workspace.settings.analyst});await refresh();nav('cases',{id:r.case.id});}
    async function submit(){await flush();const r=await mutate({op:'submit',id,attempt:attempt.current,worksheetVersion:version.current,worksheet:draft.current,status:statusRef.current});locked.current=true;version.current=r.investigation.worksheetVersion;last.current=JSON.stringify(r.investigation.worksheet);localStorage.removeItem(localKey());C(false);await refresh();T('feedback');toast.success(`Assessment submitted · ${r.investigation.feedback.score}/100`);}
    const targets:any={'Isolate Endpoint':a.host,'Disable User':a.user,'Reset Password':a.user,'Revoke Sessions':a.user,'Block IP':a.source_ip,'Block Domain':a.domain,'Quarantine File':a.hash,'Quarantine Email':a.id};
    return <><Heading eyebrow={`INVESTIGATION / ${id} / ATTEMPT ${inv.attempt||1}`} title={a.name} description={a.summary}><Badge>{a.severity}</Badge><Badge>{inv.status}</Badge>{!!inv.hintsUsed&&<Badge>Assisted attempt</Badge>}</Heading>
    {data.legacy&&<div className="note">Earlier dataset · original notes, evidence and results are preserved. {data.updatedExercise&&<Button variant="outline" onClick={()=>nav('alert',{id:data.updatedExercise})}>Open corrected exercise</Button>}</div>}
    {data.archived&&<div className="note">Archived attempt · notes, raw evidence, case and result are preserved. <Button variant="outline" onClick={()=>nav('alert',{id})}>Return to current attempt</Button></div>}
    {saveError&&<div className="note" role="alert"><p>{saveError}</p><div className="toolbar"><Button variant="outline" onClick={()=>download(id+'-local-draft.json',{worksheet:w,attempt:attempt.current,worksheetVersion:version.current,status})}>Export local draft</Button><Button variant="outline" onClick={()=>perform(async()=>{const latest=await request({view:'alert',id});localStorage.setItem(localKey()+'-recovered',JSON.stringify({worksheet:draft.current,status:statusRef.current}));localStorage.removeItem(localKey());conflict.current='';SE('');adopt(latest.investigation);await refresh();})}>Load saved worksheet</Button></div><p className="text-xs">A recovery copy of the local draft stays in this browser.</p></div>}
    <div className="toolbar"><Button variant="outline" onClick={()=>nav('ioc',{q:a.source_ip})}>Enrich source IP</Button><Button variant="outline" onClick={()=>nav('user',{id:a.user})}>Inspect identity</Button><Button variant="outline" onClick={()=>nav('host',{id:a.host})}>Inspect endpoint</Button><Button variant="outline" onClick={()=>nav('siem',{q:`source_ip = "${a.source_ip}" OR destination_ip = "${a.source_ip}"`})}>Search SIEM</Button><Button variant="outline" onClick={()=>nav('network',{q:`host = "${a.host}"`})}>Network telemetry</Button>{a.family==='Email'&&<Button variant="outline" onClick={()=>nav('email',{q:`alert_id = "${a.id}"`})}>Review message</Button>}<Button variant="outline" disabled={readOnly} onClick={()=>R(true)}>Response actions</Button><Button variant="outline" disabled={busy||readOnly} onClick={()=>perform(async()=>{await flush();const r=await mutate({op:'hint',id,attempt:attempt.current});H(r.hint);await refresh();})}>Optional hint ({inv.hintsUsed||0}/3)</Button></div>
    {hint&&<div className="note" role="status"><strong>Investigation hint:</strong> {hint}<p className="text-xs">Hints are recorded on this attempt and do not reveal the verdict.</p></div>}
    <Panel><div className="grid3"><KeyValues data={{endpoint:a.host,user:a.user,source:a.source}}/><KeyValues data={{sourceIP:a.source_ip,country:a.country,ASN:a.asn}}/><KeyValues data={{firstSeen:a.firstSeen,lastSeen:a.lastSeen,technique:a.technique}}/></div><div className="timeline-summary"><Pivot view="ioc" id={a.domain}/><Pivot view="ioc" id={a.hash}/>{a.incident_id&&<Pivot view="incidents" id={a.incident_id}/>}</div></Panel>
    <Tabs value={tab} onValueChange={T}><TabsList><TabsTrigger value="timeline">Timeline ({data.events.length})</TabsTrigger><TabsTrigger value="evidence">Evidence ({inv.bookmarks.length})</TabsTrigger><TabsTrigger value="worksheet">Investigation worksheet</TabsTrigger><TabsTrigger value="related">Related scope ({linked.length})</TabsTrigger><TabsTrigger value="handoff">Case & handoff</TabsTrigger>{inv.feedback&&<TabsTrigger value="feedback">Assessment feedback</TabsTrigger>}<TabsTrigger value="attempts">Attempt history</TabsTrigger></TabsList>
    <TabsContent value="timeline"><Panel title="Correlated event timeline" detail="Oldest first · inspect a record to bookmark it"><Events rows={data.events}/></Panel><Button onClick={()=>T('worksheet')}>Document findings →</Button></TabsContent>
    <TabsContent value="evidence"><Panel title="Preserved evidence" detail="Bookmarks belong to this attempt"><Events rows={data.bookmarkedEvents}/></Panel><p>Preserve relevant records and cite their IDs with actual observations in the worksheet.</p></TabsContent>
    <TabsContent value="worksheet"><Panel title="Analyst worksheet" detail={readOnly?'Read-only':saveError?'Draft needs attention':JSON.stringify(w)!==last.current?'Saving draft…':saved?'Saved '+new Date(saved).toLocaleTimeString():'Draft'}><fieldset disabled={readOnly} className="space-y-5"><div className="form-grid">{worksheetFields.map(([key,label])=><label className="field" key={key}><span>{label}</span><Textarea aria-label={label} value={w[key]} maxLength={5000} placeholder={key==='scope'?'Cite records supporting each affected asset and qualify unconfirmed activity.':key==='nextStep'?'State who should do what next and which evidence is needed.':'Cite record IDs and actual observations, including contradictory evidence.'} onChange={e=>W({...w,[key]:e.target.value})}/></label>)}</div><div className="form-grid"><Pick label="Verdict" value={w.verdict} options={[{value:'',label:'Choose verdict'},...verdicts]} onChange={v=>W({...w,verdict:v})}/><Pick label="Assessed severity" value={w.severity} options={severities} onChange={v=>W({...w,severity:v})}/><Pick label="Disposition" value={w.disposition} options={[{value:'',label:'Choose disposition'},...dispositions]} onChange={v=>W({...w,disposition:v})}/><Pick label="Investigation status" value={status} options={['Assigned','Investigating','Pending']} onChange={ST}/></div></fieldset><div className="statusline"><span>{inv.bookmarks.length} bookmarks · Reviewed: {inv.reviewed.join(', ')||'timeline'}</span>{saved&&<When value={saved}/>}</div><div className="toolbar"><Button disabled={busy||readOnly} onClick={()=>perform(async()=>{await flush();await refresh();toast.success('Investigation saved');})}>Save investigation</Button><Button variant="outline" disabled={busy||data.readOnly&&!c} onClick={()=>c?nav('cases',{id:c.id}):perform(createCase)}>{c?'Open case':'Create case'}</Button><Button disabled={busy||readOnly} onClick={()=>C(true)}>Submit assessment</Button></div><p className="text-xs">Scoring checks record references, observations, scope and rationale. Repeated filler earns no documentation credit. Scenario truth is hidden until submission.</p></Panel></TabsContent>
    <TabsContent value="related"><RelationshipView alerts={[a]} events={data.events}/><Panel title="Shared entities and infrastructure" detail="Association does not establish compromise"><AlertRows alerts={linked}/></Panel>{a.incident_id&&<Button onClick={()=>nav('incidents',{id:a.incident_id})}>Open incident relationships</Button>}</TabsContent>
    <TabsContent value="handoff"><Panel title="Structured handoff"><div className="toolbar"><Button disabled={busy||data.readOnly&&!c} onClick={()=>c?nav('cases',{id:c.id}):perform(createCase)}>{c?'Open '+c.id:'Create case'}</Button>{c&&<Button variant="outline" disabled={busy||data.archived} onClick={()=>perform(async()=>{await flush();const latest=await request({view:'alert',id});await mutate({op:'caseSync',id,caseId:c.id,caseVersion:latest.case.revision||0});await refresh();toast.success('Handoff updated; case notes preserved');})}>Update handoff from investigation</Button>}<Button variant="outline" onClick={()=>copy(handoff(a,liveInv()))}>Copy handoff</Button><Button variant="outline" onClick={()=>downloadText(`${id}-attempt-${inv.attempt||1}.md`,markdownReport(a,liveInv(),data.bookmarkedEvents,c,actions))}>Download Markdown report</Button><Button variant="outline" onClick={()=>download(id+'-investigation.json',{alert:a,investigation:liveInv(),evidence:data.bookmarkedEvents,actions})}>Export JSON</Button></div><pre className="case-summary">{handoff(a,liveInv())}</pre></Panel><Panel title="Simulated response log">{actions.length?actions.map((x:any)=><div className="note" key={x.id}><strong>{x.action}</strong> · {x.target}<p>{x.reason} · <When value={x.time}/></p></div>):<p>No response actions recorded in this attempt.</p>}</Panel></TabsContent>
    <TabsContent value="feedback">{inv.feedback&&<><div className="equalcol"><Panel title="Assessment result"><div className="bigscore">{inv.feedback.score}<span className="muted text-xl"> / 100</span></div><div className="chip-list"><Badge>{inv.feedback.groundTruth}</Badge><Badge>{inv.feedback.difficulty}</Badge></div><p>{inv.feedback.reason}</p><p>Elapsed time: {Math.round(inv.feedback.durationSeconds/60)} minutes, including time away.</p>{typeof inv.feedback.evidenceCoverage==='number'&&<p>Required evidence coverage: <strong>{inv.feedback.evidenceCoverage}%</strong>.</p>}{inv.feedback.contradictions?.length>0&&<div className="note"><strong>Contradictions detected</strong><ul>{inv.feedback.contradictions.map((x:string)=><li key={x}>→ {x}</li>)}</ul></div>}<p className="text-xs">{inv.feedback.rubricVersion||'Original rubric'}. Evidence matching is a transparent heuristic; it validates cited event IDs, scenario facts and contradictory conclusions; it does not replace human review of the reasoning.</p></Panel><Panel title="Scoring dimensions">{Object.entries(inv.feedback.dimensions).map(([k,v]:any)=><div className="barrow" key={k} style={{gridTemplateColumns:'170px 1fr 35px'}}><span>{k}</span><span className="bartrack"><span className="barfill block" style={{width:v+'%'}}/></span><span>{v}%</span></div>)}</Panel></div><div className="equalcol"><Panel title="What you did well"><ul className="space-y-3 muted">{inv.feedback.correct.map((s:string)=><li key={s}>✓ {s}</li>)}</ul></Panel><Panel title="What to improve"><ul className="space-y-3 muted">{inv.feedback.missed.map((s:string)=><li key={s}>→ {s}</li>)}</ul>{!inv.feedback.missed.length&&<p>All rubric dimensions were addressed.</p>}</Panel></div><Panel title="Scenario evidence and qualifications" detail="Revealed after submission">{(inv.feedback.evidence||[]).map((f:any)=><div className="note" key={f.area}><Badge>{f.role}</Badge>{f.effect&&<Badge>{f.effect.replaceAll('_',' ')}</Badge>} <button className="link" onClick={()=>inspect(data.events.find((e:any)=>e.id===f.eventId)||data.bookmarkedEvents.find((e:any)=>e.id===f.eventId))}>{f.eventId}</button><p>{f.observation}</p><p>{f.interpretation}</p></div>)}</Panel>{!data.readOnly&&<Button disabled={busy} onClick={()=>perform(async()=>{await mutate({op:'retry',id,attempt:inv.attempt});init.current='';await refresh();T('timeline');H('');toast.success('New attempt started. Previous notes, evidence and results are preserved.');})}>Start new attempt — preserve this result</Button>}</>}</TabsContent>
    <TabsContent value="attempts"><Panel title="Attempt history" detail="Notes, evidence, cases and results remain available">{data.attempts.map((x:any)=><div className="note" key={x.attempt}><strong>Attempt {x.attempt}</strong> · {x.score}/100 · {x.hintsUsed?'Assisted':'Unassisted'} · <When value={x.submitted_at}/><div className="toolbar"><Button variant="outline" onClick={()=>nav('alert',{id,attempt:String(x.attempt),tab:'feedback'})}>Review preserved attempt</Button><Button variant="outline" onClick={()=>perform(async()=>{const r=await request({view:'report',id,attempt:x.attempt});downloadText(r.filename,r.markdown);})}>Download Markdown report</Button></div></div>)}{!data.attempts.length&&<p>No previous attempts. Submit this assessment to unlock feedback and retry.</p>}</Panel></TabsContent></Tabs>
    <AlertDialog open={confirm} onOpenChange={C}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Submit this assessment?</AlertDialogTitle><AlertDialogDescription>Your verdict, notes and evidence will be locked for this attempt, then feedback becomes available. A new attempt preserves this result.</AlertDialogDescription></AlertDialogHeader><KeyValues data={{verdict:w.verdict||'Not chosen',disposition:w.disposition||'Not chosen',bookmarks:inv.bookmarks.length,case:c?.id||'Not created'}}/><AlertDialogFooter><AlertDialogCancel>Continue investigating</AlertDialogCancel><Button disabled={busy} onClick={()=>perform(submit)}>{busy?'Submitting…':'Confirm submission'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={respond} onOpenChange={R}><DialogContent><DialogHeader><DialogTitle>Simulated response action</DialogTitle><DialogDescription>Record a reason and confirm the target. Actions update this training environment only.</DialogDescription></DialogHeader><Pick label="Response action" value={action} onChange={A} options={Object.keys(targets).filter(k=>k!=='Quarantine Email'||data.events.some((e:any)=>e.kind==='email'))}/><div className="note">Target: <span className="mono">{targets[action]}</span></div><label className="field"><span>Reason for response</span><Textarea aria-label="Reason for response" value={reason} onChange={e=>N(e.target.value)}/></label><Button disabled={busy||reason.trim().length<15} onClick={()=>perform(async()=>{await flush();await mutate({op:'action',id,attempt:attempt.current,action,reason,confirmed:true});N('');R(false);await refresh();toast.success('Simulated action recorded');})}>Confirm simulated action</Button></DialogContent></Dialog></>;
}
