'use client';
import { useEffect,useState } from 'react';
import { Panel,Pick,Loading,GridTable,Button,request,useLab } from './common';
export function RelationshipView({alerts,events:supplied}:{alerts:any[];events?:any[]}){
    const {workspace,nav,inspect,revision}=useLab(),[selected,S]=useState(alerts[0]?.id||''),[records,R]=useState<any[]|null>(supplied||null),[error,E]=useState(''),a=alerts.find(x=>x.id===selected)||alerts[0];
    useEffect(()=>{if(supplied){R(supplied);return;}if(!a)return;let alive=true;R(null);E('');const q=`alert_id = "${a.id}" | sort by timestamp asc | take 100`;request({view:'events',q,active:a.id}).then(async first=>{const pages=await Promise.all(Array.from({length:Math.ceil(first.total/100)-1},(_,n)=>request({view:'events',q,active:a.id,page:n+2})));if(alive)R([first,...pages].flatMap(x=>x.rows));}).catch(e=>{if(alive)E(e.message);});return()=>{alive=false;};},[a?.id,supplied,revision]);
    if(!a)return null;if(!records)return <Panel title="Incident relationships"><Loading error={error}/></Panel>;
    const rows=records.filter(e=>e.alert_id===a.id),processes=rows.filter(e=>e.kind==='process'&&e.data.commandLine&&e.data.pid),edges:any[]=[],seen=new Set<string>();
    const add=(from:string,to:string,relation:string,e:any,fromView:string,toView:string)=>{const key=[from,to,relation].join(':');if(seen.has(key))return;seen.add(key);edges.push({id:key,from,to,relation,record:e,fromView,toView});};
    for(const e of processes){add(e.user,e.host,'Execution on endpoint',e,'user','host');const p=processes.find(x=>x.host===e.host&&x.data.pid===e.data.ppid);if(p)add(`${p.process_name} · PID ${p.data.pid}`,`${e.process_name} · PID ${e.data.pid}`,'Parent process',e,'process','process');else add(e.host,`${e.process_name} · PID ${e.data.pid}`,'Session process',e,'host','process');}
    for(const e of rows.filter(e=>['dns','network'].includes(e.kind))){const p=processes.find(x=>x.host===e.host&&x.data.pid===e.data.pid),domain=e.data.query||e.domain;if(p&&domain)add(`${p.process_name} · PID ${p.data.pid}`,domain,e.kind==='dns'?'DNS query':'Connection / hostname',e,'process','ioc');const target=workspace.hosts.find((h:any)=>h.ip===e.destination_ip&&h.id!==e.host);if(target&&e.kind==='network')add(e.host,target.id,`${e.data.protocol} / ${e.data.destinationPort} · ${e.data.firewallAction}`,e,'host','host');}
    const nodes=new Map<string,any>();for(const e of edges){nodes.set(e.from,{type:e.fromView,record:e.record});nodes.set(e.to,{type:e.toView,record:e.record});}const positions=new Map<string,any>();let max=1;[['user','host'],['process'],['ioc']].forEach((types,col)=>{const items=[...nodes].filter(([,n])=>types.includes(n.type));max=Math.max(max,items.length);items.forEach(([key],n)=>positions.set(key,{x:col*310+15,y:n*100+25}));});
    const open=(label:string,type:string,record:any)=>type==='process'?inspect(processes.find(x=>`${x.process_name} · PID ${x.data.pid}`===label)||record):nav(type,type==='ioc'?{q:label}:{id:label});
    return <Panel title="Evidence relationships" detail="Every edge links to its source record">{alerts.length>1&&<div className="toolbar"><Pick label="Incident stage" value={a.id} onChange={S} options={alerts.map(x=>({value:x.id,label:x.id+' · '+x.name}))}/><Button variant="outline" onClick={()=>nav('alert',{id:a.id})}>Open selected investigation</Button></div>}<p>Observed user, endpoint, process and destination relationships. Include endpoints in affected scope only when their records support that conclusion.</p><div className="relationship-graph"><svg viewBox={`0 0 930 ${max*100+20}`} role="img" aria-label={`Evidence relationships for ${a.id}`}><defs><marker id="relation-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#6bdcc0"/></marker></defs>{edges.map(e=>{const f=positions.get(e.from),t=positions.get(e.to);return <path key={e.id} d={f.x===t.x?`M${f.x+270},${f.y+32} C${f.x+300},${f.y+32} ${t.x+300},${t.y+32} ${t.x+270},${t.y+32}`:`M${f.x+270},${f.y+32} C${f.x+292},${f.y+32} ${t.x-20},${t.y+32} ${t.x},${t.y+32}`} fill="none" stroke="#426f72" strokeWidth="1.5" markerEnd="url(#relation-arrow)"><title>{e.relation} · {e.record.id}</title></path>;})}{[...nodes].map(([key,n])=>{const p=positions.get(key);return <g key={key} role="button" tabIndex={0} aria-label={`Inspect ${n.type} ${key}`} onClick={()=>open(key,n.type,n.record)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(key,n.type,n.record);}}} className="relation-node"><rect x={p.x} y={p.y} width={270} height={64} rx={8} fill="#152131" stroke="#487474"/><text x={p.x+12} y={p.y+21} fill="#91b5bf" fontSize={11}>{n.type.toUpperCase()}</text><text x={p.x+12} y={p.y+44} fill="#e4eef5" fontSize={12}>{key.length>34?key.slice(0,31)+'…':key}</text><title>{key}</title></g>;})}</svg></div><GridTable rows={edges} columns={[{key:'from',label:'From',render:(e:any)=><button className="link" onClick={()=>open(e.from,e.fromView,e.record)}>{e.from}</button>},{key:'relation',label:'Observed relationship'},{key:'to',label:'To',render:(e:any)=><button className="link" onClick={()=>open(e.to,e.toView,e.record)}>{e.to}</button>},{key:'record',label:'Evidence',render:(e:any)=><button className="link" onClick={()=>inspect(e.record)}>{e.record.id}</button>}]}/></Panel>;
}
