import { sqliteTable, text, integer, index, primaryKey } from 'drizzle-orm/sqlite-core';
export const labUsers = sqliteTable('users', { id: text('id').primaryKey(), data: text('data').notNull() });
export const hosts = sqliteTable('hosts', { id: text('id').primaryKey(), user: text('user').notNull(), ip: text('ip').notNull(), data: text('data').notNull() }, t => [index('idx_hosts_user').on(t.user), index('idx_hosts_ip').on(t.ip)]);
export const rules = sqliteTable('detection_rules', { id: text('id').primaryKey(), data: text('data').notNull() });
export const incidents = sqliteTable('incidents', { id: text('id').primaryKey(), name: text('name').notNull(), data: text('data').notNull() });
export const alerts = sqliteTable('alerts', { id: text('id').primaryKey(), incident_id: text('incident_id'), time: text('time').notNull(), severity: text('severity').notNull(), family: text('family').notNull(), user: text('user').notNull(), host: text('host').notNull(), source_ip: text('source_ip').notNull(), domain: text('domain').notNull(), rule_id: text('rule_id').notNull(), data: text('data').notNull() }, t => [index('idx_alerts_time').on(t.time), index('idx_alerts_incident').on(t.incident_id), index('idx_alerts_host').on(t.host), index('idx_alerts_user').on(t.user), index('idx_alerts_ip').on(t.source_ip), index('idx_alerts_domain').on(t.domain), index('idx_alerts_filter').on(t.family, t.severity)]);
export const events = sqliteTable('events', { id: text('id').primaryKey(), alert_id: text('alert_id').notNull(), incident_id: text('incident_id'), timestamp: text('timestamp').notNull(), kind: text('kind').notNull(), event_id: integer('event_id').notNull(), user: text('user').notNull(), host: text('host').notNull(), source_ip: text('source_ip').notNull(), domain: text('domain').notNull(), hash: text('hash').notNull(), process_name: text('process_name').notNull(), data: text('data').notNull() }, t => [index('idx_events_alert_time').on(t.alert_id, t.timestamp), index('idx_events_host_time').on(t.host, t.timestamp), index('idx_events_user_time').on(t.user, t.timestamp), index('idx_events_ip_time').on(t.source_ip, t.timestamp), index('idx_events_kind_time').on(t.kind, t.timestamp), index('idx_events_domain').on(t.domain), index('idx_events_hash').on(t.hash), index('idx_events_event_id').on(t.event_id), index('idx_events_time').on(t.timestamp)]);
export const iocs = sqliteTable('iocs', { value: text('value').primaryKey(), type: text('type').notNull(), data: text('data').notNull() });
export const groundTruth = sqliteTable('scenario_truth', { alert_id: text('alert_id').primaryKey(), data: text('data').notNull() });
export const investigations = sqliteTable('investigations', { owner: text('owner').notNull(), alert_id: text('alert_id').notNull(), status: text('status').notNull(), started_at: text('started_at').notNull(), updated_at: text('updated_at').notNull(), submitted_at: text('submitted_at'), data: text('data').notNull() }, t => [primaryKey({ columns: [t.owner, t.alert_id] }), index('idx_investigations_owner_status').on(t.owner, t.status)]);
export const investigationBookmarks = sqliteTable('investigation_bookmarks', { owner: text('owner').notNull(), alert_id: text('alert_id').notNull(), attempt: integer('attempt').notNull(), event_id: text('event_id').notNull(), created_at: text('created_at').notNull() }, t => [primaryKey({ columns: [t.owner, t.alert_id, t.attempt, t.event_id] }), index('idx_investigation_bookmarks_owner_alert').on(t.owner, t.alert_id, t.attempt)]);
export const cases = sqliteTable('cases', { id: text('id').primaryKey(), owner: text('owner').notNull(), alert_id: text('alert_id').notNull(), status: text('status').notNull(), data: text('data').notNull() }, t => [index('idx_cases_owner').on(t.owner), index('idx_cases_alert').on(t.owner, t.alert_id)]);
export const actions = sqliteTable('actions', { id: text('id').primaryKey(), owner: text('owner').notNull(), alert_id: text('alert_id').notNull(), target: text('target').notNull(), action: text('action').notNull(), time: text('time').notNull(), reason: text('reason').notNull() }, t => [index('idx_actions_owner_alert').on(t.owner, t.alert_id), index('idx_actions_target').on(t.owner, t.target)]);
export const settings = sqliteTable('settings', { owner: text('owner').primaryKey(), data: text('data').notNull() });
export const seedBatches = sqliteTable('seed_batches', { id: text('id').primaryKey(), time: text('time').notNull() });

export const attempts = sqliteTable('attempts', { owner: text('owner').notNull(), alert_id: text('alert_id').notNull(), attempt: integer('attempt').notNull(), data: text('data').notNull() }, t => [primaryKey({ columns: [t.owner, t.alert_id, t.attempt] })]);
